// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mock_deps_test.go -package=agent
//

// Package agent is a generated GoMock package.
package agent

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	llm "github.com/pushkaranand/finagent/internal/llm"
	sqlcgen "github.com/pushkaranand/finagent/internal/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockchatProvider is a mock of chatProvider interface.
type MockchatProvider struct {
	ctrl     *gomock.Controller
	recorder *MockchatProviderMockRecorder
	isgomock struct{}
}

// MockchatProviderMockRecorder is the mock recorder for MockchatProvider.
type MockchatProviderMockRecorder struct {
	mock *MockchatProvider
}

// NewMockchatProvider creates a new mock instance.
func NewMockchatProvider(ctrl *gomock.Controller) *MockchatProvider {
	mock := &MockchatProvider{ctrl: ctrl}
	mock.recorder = &MockchatProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatProvider) EXPECT() *MockchatProviderMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockchatProvider) Chat(ctx context.Context, req llm.ChatRequest) (llm.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(llm.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockchatProviderMockRecorder) Chat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockchatProvider)(nil).Chat), ctx, req)
}

// MockconvStore is a mock of convStore interface.
type MockconvStore struct {
	ctrl     *gomock.Controller
	recorder *MockconvStoreMockRecorder
	isgomock struct{}
}

// MockconvStoreMockRecorder is the mock recorder for MockconvStore.
type MockconvStoreMockRecorder struct {
	mock *MockconvStore
}

// NewMockconvStore creates a new mock instance.
func NewMockconvStore(ctrl *gomock.Controller) *MockconvStore {
	mock := &MockconvStore{ctrl: ctrl}
	mock.recorder = &MockconvStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconvStore) EXPECT() *MockconvStoreMockRecorder {
	return m.recorder
}

// GetOrCreateSession mocks base method.
func (m *MockconvStore) GetOrCreateSession(ctx context.Context, userID, sessionID string, ch sqlcgen.ChannelEnum) (*sqlcgen.ConversationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateSession", ctx, userID, sessionID, ch)
	ret0, _ := ret[0].(*sqlcgen.ConversationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateSession indicates an expected call of GetOrCreateSession.
func (mr *MockconvStoreMockRecorder) GetOrCreateSession(ctx, userID, sessionID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateSession", reflect.TypeOf((*MockconvStore)(nil).GetOrCreateSession), ctx, userID, sessionID, ch)
}

// RecentMessages mocks base method.
func (m *MockconvStore) RecentMessages(ctx context.Context, sessionID uuid.UUID, limit int32) ([]sqlcgen.ConversationMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentMessages", ctx, sessionID, limit)
	ret0, _ := ret[0].([]sqlcgen.ConversationMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentMessages indicates an expected call of RecentMessages.
func (mr *MockconvStoreMockRecorder) RecentMessages(ctx, sessionID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentMessages", reflect.TypeOf((*MockconvStore)(nil).RecentMessages), ctx, sessionID, limit)
}

// SaveMessage mocks base method.
func (m *MockconvStore) SaveMessage(ctx context.Context, sessionID uuid.UUID, role sqlcgen.MsgRoleEnum, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, sessionID, role, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockconvStoreMockRecorder) SaveMessage(ctx, sessionID, role, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockconvStore)(nil).SaveMessage), ctx, sessionID, role, content)
}

// MockmemStore is a mock of memStore interface.
type MockmemStore struct {
	ctrl     *gomock.Controller
	recorder *MockmemStoreMockRecorder
	isgomock struct{}
}

// MockmemStoreMockRecorder is the mock recorder for MockmemStore.
type MockmemStoreMockRecorder struct {
	mock *MockmemStore
}

// NewMockmemStore creates a new mock instance.
func NewMockmemStore(ctrl *gomock.Controller) *MockmemStore {
	mock := &MockmemStore{ctrl: ctrl}
	mock.recorder = &MockmemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmemStore) EXPECT() *MockmemStoreMockRecorder {
	return m.recorder
}

// Recall mocks base method.
func (m *MockmemStore) Recall(ctx context.Context, userID string, queryTags []string, limit int32) ([]sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, userID, queryTags, limit)
	ret0, _ := ret[0].([]sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockmemStoreMockRecorder) Recall(ctx, userID, queryTags, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockmemStore)(nil).Recall), ctx, userID, queryTags, limit)
}

// MockuserStore is a mock of userStore interface.
type MockuserStore struct {
	ctrl     *gomock.Controller
	recorder *MockuserStoreMockRecorder
	isgomock struct{}
}

// MockuserStoreMockRecorder is the mock recorder for MockuserStore.
type MockuserStoreMockRecorder struct {
	mock *MockuserStore
}

// NewMockuserStore creates a new mock instance.
func NewMockuserStore(ctrl *gomock.Controller) *MockuserStore {
	mock := &MockuserStore{ctrl: ctrl}
	mock.recorder = &MockuserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStore) EXPECT() *MockuserStoreMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserStore) GetByID(ctx context.Context, id string) (*sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserStore)(nil).GetByID), ctx, id)
}

// MocktoolRegistry is a mock of toolRegistry interface.
type MocktoolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MocktoolRegistryMockRecorder
	isgomock struct{}
}

// MocktoolRegistryMockRecorder is the mock recorder for MocktoolRegistry.
type MocktoolRegistryMockRecorder struct {
	mock *MocktoolRegistry
}

// NewMocktoolRegistry creates a new mock instance.
func NewMocktoolRegistry(ctrl *gomock.Controller) *MocktoolRegistry {
	mock := &MocktoolRegistry{ctrl: ctrl}
	mock.recorder = &MocktoolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktoolRegistry) EXPECT() *MocktoolRegistryMockRecorder {
	return m.recorder
}

// Definitions mocks base method.
func (m *MocktoolRegistry) Definitions() []llm.ToolDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definitions")
	ret0, _ := ret[0].([]llm.ToolDefinition)
	return ret0
}

// Definitions indicates an expected call of Definitions.
func (mr *MocktoolRegistryMockRecorder) Definitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definitions", reflect.TypeOf((*MocktoolRegistry)(nil).Definitions))
}

// Execute mocks base method.
func (m *MocktoolRegistry) Execute(ctx context.Context, name, callID, argsJSON string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, name, callID, argsJSON)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MocktoolRegistryMockRecorder) Execute(ctx, name, callID, argsJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MocktoolRegistry)(nil).Execute), ctx, name, callID, argsJSON)
}
