CREATE VIEW v_transactions AS
    SELECT
        t.id,
        t.account_id,
        t.user_id,
        t.idempotency_key,
        t.reference_number,
        t.amount,
        t.currency,
        t.direction,
        t.original_amount,
        t.original_currency,
        t.exchange_rate,
        t.description,
        t.counterparty_name,
        t.counterparty_identifier,
        t.payment_mode,
        t.txn_date,
        t.posted_date,
        t.created_at,
        e.description_normalized,
        e.category_id,
        e.transfer_id,
        e.transfer_type,
        e.refund_of_transaction_id,
        e.recurring_payment_id,
        e.notes,
        e.notes_updated_at,
        e.embedding,
        e.embedding_model,
        e.tagging_status,
        e.metadata,
        e.updated_at AS enriched_at
    FROM transactions t
    LEFT JOIN transaction_enrichments e ON e.transaction_id = t.id;
