// Code generated by MockGen. DO NOT EDIT.
// Source: queriers.go
//
// Generated by this command:
//
//	mockgen -source=queriers.go -destination=mock_queriers_test.go -package=tools
//

// Package tools is a generated GoMock package.
package tools

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	sqlcgen "github.com/pushkaranand/finagent/internal/sqlc"
	store "github.com/pushkaranand/finagent/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountQuerier is a mock of accountQuerier interface.
type MockaccountQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockaccountQuerierMockRecorder
	isgomock struct{}
}

// MockaccountQuerierMockRecorder is the mock recorder for MockaccountQuerier.
type MockaccountQuerierMockRecorder struct {
	mock *MockaccountQuerier
}

// NewMockaccountQuerier creates a new mock instance.
func NewMockaccountQuerier(ctrl *gomock.Controller) *MockaccountQuerier {
	mock := &MockaccountQuerier{ctrl: ctrl}
	mock.recorder = &MockaccountQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountQuerier) EXPECT() *MockaccountQuerierMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockaccountQuerier) ListByUser(ctx context.Context, userID string) ([]sqlcgen.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockaccountQuerierMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockaccountQuerier)(nil).ListByUser), ctx, userID)
}

// MocktransactionQuerier is a mock of transactionQuerier interface.
type MocktransactionQuerier struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionQuerierMockRecorder
	isgomock struct{}
}

// MocktransactionQuerierMockRecorder is the mock recorder for MocktransactionQuerier.
type MocktransactionQuerierMockRecorder struct {
	mock *MocktransactionQuerier
}

// NewMocktransactionQuerier creates a new mock instance.
func NewMocktransactionQuerier(ctrl *gomock.Controller) *MocktransactionQuerier {
	mock := &MocktransactionQuerier{ctrl: ctrl}
	mock.recorder = &MocktransactionQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionQuerier) EXPECT() *MocktransactionQuerierMockRecorder {
	return m.recorder
}

// GetSpendingByCategory mocks base method.
func (m *MocktransactionQuerier) GetSpendingByCategory(ctx context.Context, userID string, from, to time.Time, accountID *string) ([]store.SpendingRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpendingByCategory", ctx, userID, from, to, accountID)
	ret0, _ := ret[0].([]store.SpendingRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpendingByCategory indicates an expected call of GetSpendingByCategory.
func (mr *MocktransactionQuerierMockRecorder) GetSpendingByCategory(ctx, userID, from, to, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpendingByCategory", reflect.TypeOf((*MocktransactionQuerier)(nil).GetSpendingByCategory), ctx, userID, from, to, accountID)
}

// List mocks base method.
func (m *MocktransactionQuerier) List(ctx context.Context, p store.ListTransactionsParams) ([]sqlcgen.VTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, p)
	ret0, _ := ret[0].([]sqlcgen.VTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktransactionQuerierMockRecorder) List(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktransactionQuerier)(nil).List), ctx, p)
}

// MockrecurringQuerier is a mock of recurringQuerier interface.
type MockrecurringQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockrecurringQuerierMockRecorder
	isgomock struct{}
}

// MockrecurringQuerierMockRecorder is the mock recorder for MockrecurringQuerier.
type MockrecurringQuerierMockRecorder struct {
	mock *MockrecurringQuerier
}

// NewMockrecurringQuerier creates a new mock instance.
func NewMockrecurringQuerier(ctrl *gomock.Controller) *MockrecurringQuerier {
	mock := &MockrecurringQuerier{ctrl: ctrl}
	mock.recorder = &MockrecurringQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecurringQuerier) EXPECT() *MockrecurringQuerierMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockrecurringQuerier) List(ctx context.Context, userID string) ([]sqlcgen.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.RecurringPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrecurringQuerierMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockrecurringQuerier)(nil).List), ctx, userID)
}

// MocklabelQuerier is a mock of labelQuerier interface.
type MocklabelQuerier struct {
	ctrl     *gomock.Controller
	recorder *MocklabelQuerierMockRecorder
	isgomock struct{}
}

// MocklabelQuerierMockRecorder is the mock recorder for MocklabelQuerier.
type MocklabelQuerierMockRecorder struct {
	mock *MocklabelQuerier
}

// NewMocklabelQuerier creates a new mock instance.
func NewMocklabelQuerier(ctrl *gomock.Controller) *MocklabelQuerier {
	mock := &MocklabelQuerier{ctrl: ctrl}
	mock.recorder = &MocklabelQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklabelQuerier) EXPECT() *MocklabelQuerierMockRecorder {
	return m.recorder
}

// AddToTransaction mocks base method.
func (m *MocklabelQuerier) AddToTransaction(ctx context.Context, txnID, labelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToTransaction", ctx, txnID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToTransaction indicates an expected call of AddToTransaction.
func (mr *MocklabelQuerierMockRecorder) AddToTransaction(ctx, txnID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTransaction", reflect.TypeOf((*MocklabelQuerier)(nil).AddToTransaction), ctx, txnID, labelID)
}

// FindOrCreate mocks base method.
func (m *MocklabelQuerier) FindOrCreate(ctx context.Context, userID, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, userID, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MocklabelQuerierMockRecorder) FindOrCreate(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MocklabelQuerier)(nil).FindOrCreate), ctx, userID, name)
}

// RemoveFromTransaction mocks base method.
func (m *MocklabelQuerier) RemoveFromTransaction(ctx context.Context, txnID, labelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromTransaction", ctx, txnID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromTransaction indicates an expected call of RemoveFromTransaction.
func (mr *MocklabelQuerierMockRecorder) RemoveFromTransaction(ctx, txnID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromTransaction", reflect.TypeOf((*MocklabelQuerier)(nil).RemoveFromTransaction), ctx, txnID, labelID)
}

// MockmemoryQuerier is a mock of memoryQuerier interface.
type MockmemoryQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockmemoryQuerierMockRecorder
	isgomock struct{}
}

// MockmemoryQuerierMockRecorder is the mock recorder for MockmemoryQuerier.
type MockmemoryQuerierMockRecorder struct {
	mock *MockmemoryQuerier
}

// NewMockmemoryQuerier creates a new mock instance.
func NewMockmemoryQuerier(ctrl *gomock.Controller) *MockmemoryQuerier {
	mock := &MockmemoryQuerier{ctrl: ctrl}
	mock.recorder = &MockmemoryQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmemoryQuerier) EXPECT() *MockmemoryQuerierMockRecorder {
	return m.recorder
}

// Recall mocks base method.
func (m *MockmemoryQuerier) Recall(ctx context.Context, userID, query string, limit int32) ([]sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, userID, query, limit)
	ret0, _ := ret[0].([]sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockmemoryQuerierMockRecorder) Recall(ctx, userID, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockmemoryQuerier)(nil).Recall), ctx, userID, query, limit)
}

// Save mocks base method.
func (m *MockmemoryQuerier) Save(ctx context.Context, userID *string, content string, memType sqlcgen.MemoryTypeEnum, tags []string) (*sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, content, memType, tags)
	ret0, _ := ret[0].(*sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockmemoryQuerierMockRecorder) Save(ctx, userID, content, memType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockmemoryQuerier)(nil).Save), ctx, userID, content, memType, tags)
}

// MockzerodhaQuerier is a mock of zerodhaQuerier interface.
type MockzerodhaQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockzerodhaQuerierMockRecorder
	isgomock struct{}
}

// MockzerodhaQuerierMockRecorder is the mock recorder for MockzerodhaQuerier.
type MockzerodhaQuerierMockRecorder struct {
	mock *MockzerodhaQuerier
}

// NewMockzerodhaQuerier creates a new mock instance.
func NewMockzerodhaQuerier(ctrl *gomock.Controller) *MockzerodhaQuerier {
	mock := &MockzerodhaQuerier{ctrl: ctrl}
	mock.recorder = &MockzerodhaQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockzerodhaQuerier) EXPECT() *MockzerodhaQuerierMockRecorder {
	return m.recorder
}

// GetEquityHoldings mocks base method.
func (m *MockzerodhaQuerier) GetEquityHoldings(ctx context.Context, userID string) ([]sqlcgen.ZerodhaEquityHolding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEquityHoldings", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.ZerodhaEquityHolding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEquityHoldings indicates an expected call of GetEquityHoldings.
func (mr *MockzerodhaQuerierMockRecorder) GetEquityHoldings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEquityHoldings", reflect.TypeOf((*MockzerodhaQuerier)(nil).GetEquityHoldings), ctx, userID)
}

// GetEquityHoldingsByType mocks base method.
func (m *MockzerodhaQuerier) GetEquityHoldingsByType(ctx context.Context, userID string) ([]sqlcgen.GetZerodhaEquityHoldingsByTypeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEquityHoldingsByType", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.GetZerodhaEquityHoldingsByTypeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEquityHoldingsByType indicates an expected call of GetEquityHoldingsByType.
func (mr *MockzerodhaQuerierMockRecorder) GetEquityHoldingsByType(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEquityHoldingsByType", reflect.TypeOf((*MockzerodhaQuerier)(nil).GetEquityHoldingsByType), ctx, userID)
}

// GetEquitySummary mocks base method.
func (m *MockzerodhaQuerier) GetEquitySummary(ctx context.Context, userID string) (sqlcgen.GetZerodhaEquitySummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEquitySummary", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.GetZerodhaEquitySummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEquitySummary indicates an expected call of GetEquitySummary.
func (mr *MockzerodhaQuerierMockRecorder) GetEquitySummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEquitySummary", reflect.TypeOf((*MockzerodhaQuerier)(nil).GetEquitySummary), ctx, userID)
}

// GetMFHoldings mocks base method.
func (m *MockzerodhaQuerier) GetMFHoldings(ctx context.Context, userID string) ([]sqlcgen.ZerodhaMfHolding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMFHoldings", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.ZerodhaMfHolding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMFHoldings indicates an expected call of GetMFHoldings.
func (mr *MockzerodhaQuerierMockRecorder) GetMFHoldings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMFHoldings", reflect.TypeOf((*MockzerodhaQuerier)(nil).GetMFHoldings), ctx, userID)
}

// GetMFSummary mocks base method.
func (m *MockzerodhaQuerier) GetMFSummary(ctx context.Context, userID string) (sqlcgen.GetZerodhaMFSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMFSummary", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.GetZerodhaMFSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMFSummary indicates an expected call of GetMFSummary.
func (mr *MockzerodhaQuerierMockRecorder) GetMFSummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMFSummary", reflect.TypeOf((*MockzerodhaQuerier)(nil).GetMFSummary), ctx, userID)
}

// MockzerodhaSyncer is a mock of zerodhaSyncer interface.
type MockzerodhaSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockzerodhaSyncerMockRecorder
	isgomock struct{}
}

// MockzerodhaSyncerMockRecorder is the mock recorder for MockzerodhaSyncer.
type MockzerodhaSyncerMockRecorder struct {
	mock *MockzerodhaSyncer
}

// NewMockzerodhaSyncer creates a new mock instance.
func NewMockzerodhaSyncer(ctrl *gomock.Controller) *MockzerodhaSyncer {
	mock := &MockzerodhaSyncer{ctrl: ctrl}
	mock.recorder = &MockzerodhaSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockzerodhaSyncer) EXPECT() *MockzerodhaSyncerMockRecorder {
	return m.recorder
}

// ForceSync mocks base method.
func (m *MockzerodhaSyncer) ForceSync(ctx context.Context, userID uuid.UUID) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceSync", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForceSync indicates an expected call of ForceSync.
func (mr *MockzerodhaSyncerMockRecorder) ForceSync(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceSync", reflect.TypeOf((*MockzerodhaSyncer)(nil).ForceSync), ctx, userID)
}

// MockfdManager is a mock of fdManager interface.
type MockfdManager struct {
	ctrl     *gomock.Controller
	recorder *MockfdManagerMockRecorder
	isgomock struct{}
}

// MockfdManagerMockRecorder is the mock recorder for MockfdManager.
type MockfdManagerMockRecorder struct {
	mock *MockfdManager
}

// NewMockfdManager creates a new mock instance.
func NewMockfdManager(ctrl *gomock.Controller) *MockfdManager {
	mock := &MockfdManager{ctrl: ctrl}
	mock.recorder = &MockfdManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfdManager) EXPECT() *MockfdManagerMockRecorder {
	return m.recorder
}

// CreateWithAccount mocks base method.
func (m *MockfdManager) CreateWithAccount(ctx context.Context, p store.CreateFDParams) (*sqlcgen.FixedDeposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithAccount", ctx, p)
	ret0, _ := ret[0].(*sqlcgen.FixedDeposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithAccount indicates an expected call of CreateWithAccount.
func (mr *MockfdManagerMockRecorder) CreateWithAccount(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithAccount", reflect.TypeOf((*MockfdManager)(nil).CreateWithAccount), ctx, p)
}

// Get mocks base method.
func (m *MockfdManager) Get(ctx context.Context, id, userID string) (*sqlcgen.FixedDeposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, userID)
	ret0, _ := ret[0].(*sqlcgen.FixedDeposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockfdManagerMockRecorder) Get(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockfdManager)(nil).Get), ctx, id, userID)
}

// RenewFD mocks base method.
func (m *MockfdManager) RenewFD(ctx context.Context, p store.RenewFDParams) (*sqlcgen.FixedDeposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewFD", ctx, p)
	ret0, _ := ret[0].(*sqlcgen.FixedDeposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewFD indicates an expected call of RenewFD.
func (mr *MockfdManagerMockRecorder) RenewFD(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewFD", reflect.TypeOf((*MockfdManager)(nil).RenewFD), ctx, p)
}

// UpdateStatus mocks base method.
func (m *MockfdManager) UpdateStatus(ctx context.Context, p store.UpdateStatusParams) (*sqlcgen.FixedDeposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, p)
	ret0, _ := ret[0].(*sqlcgen.FixedDeposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockfdManagerMockRecorder) UpdateStatus(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockfdManager)(nil).UpdateStatus), ctx, p)
}

// MockfdLister is a mock of fdLister interface.
type MockfdLister struct {
	ctrl     *gomock.Controller
	recorder *MockfdListerMockRecorder
	isgomock struct{}
}

// MockfdListerMockRecorder is the mock recorder for MockfdLister.
type MockfdListerMockRecorder struct {
	mock *MockfdLister
}

// NewMockfdLister creates a new mock instance.
func NewMockfdLister(ctrl *gomock.Controller) *MockfdLister {
	mock := &MockfdLister{ctrl: ctrl}
	mock.recorder = &MockfdListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfdLister) EXPECT() *MockfdListerMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockfdLister) ListByUser(ctx context.Context, p store.ListFDsParams) ([]sqlcgen.FixedDeposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, p)
	ret0, _ := ret[0].([]sqlcgen.FixedDeposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockfdListerMockRecorder) ListByUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockfdLister)(nil).ListByUser), ctx, p)
}

// MockrawQuerier is a mock of rawQuerier interface.
type MockrawQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockrawQuerierMockRecorder
	isgomock struct{}
}

// MockrawQuerierMockRecorder is the mock recorder for MockrawQuerier.
type MockrawQuerierMockRecorder struct {
	mock *MockrawQuerier
}

// NewMockrawQuerier creates a new mock instance.
func NewMockrawQuerier(ctrl *gomock.Controller) *MockrawQuerier {
	mock := &MockrawQuerier{ctrl: ctrl}
	mock.recorder = &MockrawQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrawQuerier) EXPECT() *MockrawQuerierMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockrawQuerier) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockrawQuerierMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockrawQuerier)(nil).Query), varargs...)
}
