// Code generated by MockGen. DO NOT EDIT.
// Source: queriers.go
//
// Generated by this command:
//
//	mockgen -source=queriers.go -destination=mock_queriers_test.go -package=tools
//

// Package tools is a generated GoMock package.
package tools

import (
	context "context"
	reflect "reflect"
	time "time"

	sqlcgen "github.com/pushkaranand/finagent/internal/sqlc"
	store "github.com/pushkaranand/finagent/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountQuerier is a mock of accountQuerier interface.
type MockaccountQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockaccountQuerierMockRecorder
	isgomock struct{}
}

// MockaccountQuerierMockRecorder is the mock recorder for MockaccountQuerier.
type MockaccountQuerierMockRecorder struct {
	mock *MockaccountQuerier
}

// NewMockaccountQuerier creates a new mock instance.
func NewMockaccountQuerier(ctrl *gomock.Controller) *MockaccountQuerier {
	mock := &MockaccountQuerier{ctrl: ctrl}
	mock.recorder = &MockaccountQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountQuerier) EXPECT() *MockaccountQuerierMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockaccountQuerier) ListByUser(ctx context.Context, userID string) ([]sqlcgen.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockaccountQuerierMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockaccountQuerier)(nil).ListByUser), ctx, userID)
}

// MocktransactionQuerier is a mock of transactionQuerier interface.
type MocktransactionQuerier struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionQuerierMockRecorder
	isgomock struct{}
}

// MocktransactionQuerierMockRecorder is the mock recorder for MocktransactionQuerier.
type MocktransactionQuerierMockRecorder struct {
	mock *MocktransactionQuerier
}

// NewMocktransactionQuerier creates a new mock instance.
func NewMocktransactionQuerier(ctrl *gomock.Controller) *MocktransactionQuerier {
	mock := &MocktransactionQuerier{ctrl: ctrl}
	mock.recorder = &MocktransactionQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionQuerier) EXPECT() *MocktransactionQuerierMockRecorder {
	return m.recorder
}

// GetSpendingByCategory mocks base method.
func (m *MocktransactionQuerier) GetSpendingByCategory(ctx context.Context, userID string, from, to time.Time, accountID *string) ([]store.SpendingRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpendingByCategory", ctx, userID, from, to, accountID)
	ret0, _ := ret[0].([]store.SpendingRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpendingByCategory indicates an expected call of GetSpendingByCategory.
func (mr *MocktransactionQuerierMockRecorder) GetSpendingByCategory(ctx, userID, from, to, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpendingByCategory", reflect.TypeOf((*MocktransactionQuerier)(nil).GetSpendingByCategory), ctx, userID, from, to, accountID)
}

// List mocks base method.
func (m *MocktransactionQuerier) List(ctx context.Context, p store.ListTransactionsParams) ([]sqlcgen.VTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, p)
	ret0, _ := ret[0].([]sqlcgen.VTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktransactionQuerierMockRecorder) List(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktransactionQuerier)(nil).List), ctx, p)
}

// MockrecurringQuerier is a mock of recurringQuerier interface.
type MockrecurringQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockrecurringQuerierMockRecorder
	isgomock struct{}
}

// MockrecurringQuerierMockRecorder is the mock recorder for MockrecurringQuerier.
type MockrecurringQuerierMockRecorder struct {
	mock *MockrecurringQuerier
}

// NewMockrecurringQuerier creates a new mock instance.
func NewMockrecurringQuerier(ctrl *gomock.Controller) *MockrecurringQuerier {
	mock := &MockrecurringQuerier{ctrl: ctrl}
	mock.recorder = &MockrecurringQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecurringQuerier) EXPECT() *MockrecurringQuerierMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockrecurringQuerier) List(ctx context.Context, userID string) ([]sqlcgen.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.RecurringPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrecurringQuerierMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockrecurringQuerier)(nil).List), ctx, userID)
}

// MocklabelQuerier is a mock of labelQuerier interface.
type MocklabelQuerier struct {
	ctrl     *gomock.Controller
	recorder *MocklabelQuerierMockRecorder
	isgomock struct{}
}

// MocklabelQuerierMockRecorder is the mock recorder for MocklabelQuerier.
type MocklabelQuerierMockRecorder struct {
	mock *MocklabelQuerier
}

// NewMocklabelQuerier creates a new mock instance.
func NewMocklabelQuerier(ctrl *gomock.Controller) *MocklabelQuerier {
	mock := &MocklabelQuerier{ctrl: ctrl}
	mock.recorder = &MocklabelQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklabelQuerier) EXPECT() *MocklabelQuerierMockRecorder {
	return m.recorder
}

// AddToTransaction mocks base method.
func (m *MocklabelQuerier) AddToTransaction(ctx context.Context, txnID, labelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToTransaction", ctx, txnID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToTransaction indicates an expected call of AddToTransaction.
func (mr *MocklabelQuerierMockRecorder) AddToTransaction(ctx, txnID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTransaction", reflect.TypeOf((*MocklabelQuerier)(nil).AddToTransaction), ctx, txnID, labelID)
}

// RemoveFromTransaction mocks base method.
func (m *MocklabelQuerier) RemoveFromTransaction(ctx context.Context, txnID, labelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromTransaction", ctx, txnID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromTransaction indicates an expected call of RemoveFromTransaction.
func (mr *MocklabelQuerierMockRecorder) RemoveFromTransaction(ctx, txnID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromTransaction", reflect.TypeOf((*MocklabelQuerier)(nil).RemoveFromTransaction), ctx, txnID, labelID)
}

// MockmemoryQuerier is a mock of memoryQuerier interface.
type MockmemoryQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockmemoryQuerierMockRecorder
	isgomock struct{}
}

// MockmemoryQuerierMockRecorder is the mock recorder for MockmemoryQuerier.
type MockmemoryQuerierMockRecorder struct {
	mock *MockmemoryQuerier
}

// NewMockmemoryQuerier creates a new mock instance.
func NewMockmemoryQuerier(ctrl *gomock.Controller) *MockmemoryQuerier {
	mock := &MockmemoryQuerier{ctrl: ctrl}
	mock.recorder = &MockmemoryQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmemoryQuerier) EXPECT() *MockmemoryQuerierMockRecorder {
	return m.recorder
}

// Recall mocks base method.
func (m *MockmemoryQuerier) Recall(ctx context.Context, userID string, queryTags []string, limit int32) ([]sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, userID, queryTags, limit)
	ret0, _ := ret[0].([]sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockmemoryQuerierMockRecorder) Recall(ctx, userID, queryTags, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockmemoryQuerier)(nil).Recall), ctx, userID, queryTags, limit)
}

// Save mocks base method.
func (m *MockmemoryQuerier) Save(ctx context.Context, userID *string, content string, memType sqlcgen.MemoryTypeEnum, tags []string) (*sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, content, memType, tags)
	ret0, _ := ret[0].(*sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockmemoryQuerierMockRecorder) Save(ctx, userID, content, memType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockmemoryQuerier)(nil).Save), ctx, userID, content, memType, tags)
}
