// Code generated by MockGen. DO NOT EDIT.
// Source: ../sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=../sqlc/querier.go -destination=mock_querier_test.go -package=store
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	sqlcgen "github.com/pushkaranand/finagent/internal/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddAccountMember mocks base method.
func (m *MockQuerier) AddAccountMember(ctx context.Context, arg sqlcgen.AddAccountMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccountMember indicates an expected call of AddAccountMember.
func (mr *MockQuerierMockRecorder) AddAccountMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountMember", reflect.TypeOf((*MockQuerier)(nil).AddAccountMember), ctx, arg)
}

// AddTransactionLabel mocks base method.
func (m *MockQuerier) AddTransactionLabel(ctx context.Context, arg sqlcgen.AddTransactionLabelParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransactionLabel", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTransactionLabel indicates an expected call of AddTransactionLabel.
func (mr *MockQuerierMockRecorder) AddTransactionLabel(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransactionLabel", reflect.TypeOf((*MockQuerier)(nil).AddTransactionLabel), ctx, arg)
}

// CreateAccount mocks base method.
func (m *MockQuerier) CreateAccount(ctx context.Context, arg sqlcgen.CreateAccountParams) (sqlcgen.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockQuerierMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockQuerier)(nil).CreateAccount), ctx, arg)
}

// CreateImportRun mocks base method.
func (m *MockQuerier) CreateImportRun(ctx context.Context, arg sqlcgen.CreateImportRunParams) (sqlcgen.ImportRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImportRun", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.ImportRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImportRun indicates an expected call of CreateImportRun.
func (mr *MockQuerierMockRecorder) CreateImportRun(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImportRun", reflect.TypeOf((*MockQuerier)(nil).CreateImportRun), ctx, arg)
}

// CreateLabel mocks base method.
func (m *MockQuerier) CreateLabel(ctx context.Context, arg sqlcgen.CreateLabelParams) (sqlcgen.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockQuerierMockRecorder) CreateLabel(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockQuerier)(nil).CreateLabel), ctx, arg)
}

// CreateMemory mocks base method.
func (m *MockQuerier) CreateMemory(ctx context.Context, arg sqlcgen.CreateMemoryParams) (sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMemory", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMemory indicates an expected call of CreateMemory.
func (mr *MockQuerierMockRecorder) CreateMemory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMemory", reflect.TypeOf((*MockQuerier)(nil).CreateMemory), ctx, arg)
}

// CreateRecurringPayment mocks base method.
func (m *MockQuerier) CreateRecurringPayment(ctx context.Context, arg sqlcgen.CreateRecurringPaymentParams) (sqlcgen.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecurringPayment", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.RecurringPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecurringPayment indicates an expected call of CreateRecurringPayment.
func (mr *MockQuerierMockRecorder) CreateRecurringPayment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecurringPayment", reflect.TypeOf((*MockQuerier)(nil).CreateRecurringPayment), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockQuerier) CreateSession(ctx context.Context, arg sqlcgen.CreateSessionParams) (sqlcgen.ConversationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.ConversationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockQuerierMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockQuerier)(nil).CreateSession), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg sqlcgen.CreateUserParams) (sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeactivateMemory mocks base method.
func (m *MockQuerier) DeactivateMemory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateMemory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateMemory indicates an expected call of DeactivateMemory.
func (mr *MockQuerierMockRecorder) DeactivateMemory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateMemory", reflect.TypeOf((*MockQuerier)(nil).DeactivateMemory), ctx, id)
}

// DeactivateRecurringPayment mocks base method.
func (m *MockQuerier) DeactivateRecurringPayment(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateRecurringPayment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateRecurringPayment indicates an expected call of DeactivateRecurringPayment.
func (mr *MockQuerierMockRecorder) DeactivateRecurringPayment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateRecurringPayment", reflect.TypeOf((*MockQuerier)(nil).DeactivateRecurringPayment), ctx, id)
}

// FinishImportRun mocks base method.
func (m *MockQuerier) FinishImportRun(ctx context.Context, arg sqlcgen.FinishImportRunParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishImportRun", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishImportRun indicates an expected call of FinishImportRun.
func (mr *MockQuerierMockRecorder) FinishImportRun(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishImportRun", reflect.TypeOf((*MockQuerier)(nil).FinishImportRun), ctx, arg)
}

// GetAccountByID mocks base method.
func (m *MockQuerier) GetAccountByID(ctx context.Context, id uuid.UUID) (sqlcgen.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, id)
	ret0, _ := ret[0].(sqlcgen.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockQuerierMockRecorder) GetAccountByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockQuerier)(nil).GetAccountByID), ctx, id)
}

// GetAccountDetails mocks base method.
func (m *MockQuerier) GetAccountDetails(ctx context.Context, accountID uuid.UUID) (sqlcgen.AccountDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountDetails", ctx, accountID)
	ret0, _ := ret[0].(sqlcgen.AccountDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountDetails indicates an expected call of GetAccountDetails.
func (mr *MockQuerierMockRecorder) GetAccountDetails(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountDetails", reflect.TypeOf((*MockQuerier)(nil).GetAccountDetails), ctx, accountID)
}

// GetCategoryByID mocks base method.
func (m *MockQuerier) GetCategoryByID(ctx context.Context, id uuid.UUID) (sqlcgen.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, id)
	ret0, _ := ret[0].(sqlcgen.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockQuerierMockRecorder) GetCategoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockQuerier)(nil).GetCategoryByID), ctx, id)
}

// GetCategoryBySlug mocks base method.
func (m *MockQuerier) GetCategoryBySlug(ctx context.Context, slug string) (sqlcgen.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlcgen.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBySlug indicates an expected call of GetCategoryBySlug.
func (mr *MockQuerierMockRecorder) GetCategoryBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBySlug", reflect.TypeOf((*MockQuerier)(nil).GetCategoryBySlug), ctx, slug)
}

// GetIdempotencyKeyExists mocks base method.
func (m *MockQuerier) GetIdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdempotencyKeyExists", ctx, idempotencyKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdempotencyKeyExists indicates an expected call of GetIdempotencyKeyExists.
func (mr *MockQuerierMockRecorder) GetIdempotencyKeyExists(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdempotencyKeyExists", reflect.TypeOf((*MockQuerier)(nil).GetIdempotencyKeyExists), ctx, idempotencyKey)
}

// GetLabelBySlug mocks base method.
func (m *MockQuerier) GetLabelBySlug(ctx context.Context, slug string) (sqlcgen.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlcgen.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelBySlug indicates an expected call of GetLabelBySlug.
func (mr *MockQuerierMockRecorder) GetLabelBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelBySlug", reflect.TypeOf((*MockQuerier)(nil).GetLabelBySlug), ctx, slug)
}

// GetRecurringPaymentByID mocks base method.
func (m *MockQuerier) GetRecurringPaymentByID(ctx context.Context, id uuid.UUID) (sqlcgen.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecurringPaymentByID", ctx, id)
	ret0, _ := ret[0].(sqlcgen.RecurringPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecurringPaymentByID indicates an expected call of GetRecurringPaymentByID.
func (mr *MockQuerierMockRecorder) GetRecurringPaymentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecurringPaymentByID", reflect.TypeOf((*MockQuerier)(nil).GetRecurringPaymentByID), ctx, id)
}

// GetSession mocks base method.
func (m *MockQuerier) GetSession(ctx context.Context, id uuid.UUID) (sqlcgen.ConversationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(sqlcgen.ConversationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockQuerierMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockQuerier)(nil).GetSession), ctx, id)
}

// GetSpendingByCategory mocks base method.
func (m *MockQuerier) GetSpendingByCategory(ctx context.Context, arg sqlcgen.GetSpendingByCategoryParams) ([]sqlcgen.GetSpendingByCategoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpendingByCategory", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.GetSpendingByCategoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpendingByCategory indicates an expected call of GetSpendingByCategory.
func (mr *MockQuerierMockRecorder) GetSpendingByCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpendingByCategory", reflect.TypeOf((*MockQuerier)(nil).GetSpendingByCategory), ctx, arg)
}

// GetTransactionByID mocks base method.
func (m *MockQuerier) GetTransactionByID(ctx context.Context, id uuid.UUID) (sqlcgen.VTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, id)
	ret0, _ := ret[0].(sqlcgen.VTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockQuerierMockRecorder) GetTransactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockQuerier)(nil).GetTransactionByID), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id uuid.UUID) (sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// InsertTransaction mocks base method.
func (m *MockQuerier) InsertTransaction(ctx context.Context, arg sqlcgen.InsertTransactionParams) (sqlcgen.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockQuerierMockRecorder) InsertTransaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockQuerier)(nil).InsertTransaction), ctx, arg)
}

// InsertTransactionEnrichment mocks base method.
func (m *MockQuerier) InsertTransactionEnrichment(ctx context.Context, transactionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionEnrichment", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactionEnrichment indicates an expected call of InsertTransactionEnrichment.
func (mr *MockQuerierMockRecorder) InsertTransactionEnrichment(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionEnrichment", reflect.TypeOf((*MockQuerier)(nil).InsertTransactionEnrichment), ctx, transactionID)
}

// ListAccountsByUser mocks base method.
func (m *MockQuerier) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]sqlcgen.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsByUser indicates an expected call of ListAccountsByUser.
func (mr *MockQuerierMockRecorder) ListAccountsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsByUser", reflect.TypeOf((*MockQuerier)(nil).ListAccountsByUser), ctx, userID)
}

// ListCategories mocks base method.
func (m *MockQuerier) ListCategories(ctx context.Context) ([]sqlcgen.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]sqlcgen.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockQuerierMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockQuerier)(nil).ListCategories), ctx)
}

// ListImportRuns mocks base method.
func (m *MockQuerier) ListImportRuns(ctx context.Context, userID uuid.UUID) ([]sqlcgen.ImportRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImportRuns", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.ImportRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImportRuns indicates an expected call of ListImportRuns.
func (mr *MockQuerierMockRecorder) ListImportRuns(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImportRuns", reflect.TypeOf((*MockQuerier)(nil).ListImportRuns), ctx, userID)
}

// ListLabels mocks base method.
func (m *MockQuerier) ListLabels(ctx context.Context, userID pgtype.UUID) ([]sqlcgen.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockQuerierMockRecorder) ListLabels(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockQuerier)(nil).ListLabels), ctx, userID)
}

// ListMemories mocks base method.
func (m *MockQuerier) ListMemories(ctx context.Context, arg sqlcgen.ListMemoriesParams) ([]sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemories", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemories indicates an expected call of ListMemories.
func (mr *MockQuerierMockRecorder) ListMemories(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemories", reflect.TypeOf((*MockQuerier)(nil).ListMemories), ctx, arg)
}

// ListRecentMessages mocks base method.
func (m *MockQuerier) ListRecentMessages(ctx context.Context, arg sqlcgen.ListRecentMessagesParams) ([]sqlcgen.ConversationMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentMessages", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.ConversationMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentMessages indicates an expected call of ListRecentMessages.
func (mr *MockQuerierMockRecorder) ListRecentMessages(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentMessages", reflect.TypeOf((*MockQuerier)(nil).ListRecentMessages), ctx, arg)
}

// ListRecurringPayments mocks base method.
func (m *MockQuerier) ListRecurringPayments(ctx context.Context, userID uuid.UUID) ([]sqlcgen.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecurringPayments", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.RecurringPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecurringPayments indicates an expected call of ListRecurringPayments.
func (mr *MockQuerierMockRecorder) ListRecurringPayments(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecurringPayments", reflect.TypeOf((*MockQuerier)(nil).ListRecurringPayments), ctx, userID)
}

// ListSubCategories mocks base method.
func (m *MockQuerier) ListSubCategories(ctx context.Context, parentID pgtype.UUID) ([]sqlcgen.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubCategories", ctx, parentID)
	ret0, _ := ret[0].([]sqlcgen.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubCategories indicates an expected call of ListSubCategories.
func (mr *MockQuerierMockRecorder) ListSubCategories(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubCategories", reflect.TypeOf((*MockQuerier)(nil).ListSubCategories), ctx, parentID)
}

// ListTopLevelCategories mocks base method.
func (m *MockQuerier) ListTopLevelCategories(ctx context.Context) ([]sqlcgen.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopLevelCategories", ctx)
	ret0, _ := ret[0].([]sqlcgen.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopLevelCategories indicates an expected call of ListTopLevelCategories.
func (mr *MockQuerierMockRecorder) ListTopLevelCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopLevelCategories", reflect.TypeOf((*MockQuerier)(nil).ListTopLevelCategories), ctx)
}

// ListTransactionLabels mocks base method.
func (m *MockQuerier) ListTransactionLabels(ctx context.Context, transactionID uuid.UUID) ([]sqlcgen.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionLabels", ctx, transactionID)
	ret0, _ := ret[0].([]sqlcgen.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionLabels indicates an expected call of ListTransactionLabels.
func (mr *MockQuerierMockRecorder) ListTransactionLabels(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionLabels", reflect.TypeOf((*MockQuerier)(nil).ListTransactionLabels), ctx, transactionID)
}

// ListTransactions mocks base method.
func (m *MockQuerier) ListTransactions(ctx context.Context, arg sqlcgen.ListTransactionsParams) ([]sqlcgen.VTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.VTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockQuerierMockRecorder) ListTransactions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockQuerier)(nil).ListTransactions), ctx, arg)
}

// ListTransactionsByLabel mocks base method.
func (m *MockQuerier) ListTransactionsByLabel(ctx context.Context, arg sqlcgen.ListTransactionsByLabelParams) ([]sqlcgen.VTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByLabel", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.VTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByLabel indicates an expected call of ListTransactionsByLabel.
func (mr *MockQuerierMockRecorder) ListTransactionsByLabel(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByLabel", reflect.TypeOf((*MockQuerier)(nil).ListTransactionsByLabel), ctx, arg)
}

// ListUserSessions mocks base method.
func (m *MockQuerier) ListUserSessions(ctx context.Context, arg sqlcgen.ListUserSessionsParams) ([]sqlcgen.ConversationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserSessions", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.ConversationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserSessions indicates an expected call of ListUserSessions.
func (mr *MockQuerierMockRecorder) ListUserSessions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserSessions", reflect.TypeOf((*MockQuerier)(nil).ListUserSessions), ctx, arg)
}

// ListUsers mocks base method.
func (m *MockQuerier) ListUsers(ctx context.Context) ([]sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockQuerierMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockQuerier)(nil).ListUsers), ctx)
}

// RecallMemoriesByTags mocks base method.
func (m *MockQuerier) RecallMemoriesByTags(ctx context.Context, arg sqlcgen.RecallMemoriesByTagsParams) ([]sqlcgen.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecallMemoriesByTags", ctx, arg)
	ret0, _ := ret[0].([]sqlcgen.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecallMemoriesByTags indicates an expected call of RecallMemoriesByTags.
func (mr *MockQuerierMockRecorder) RecallMemoriesByTags(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecallMemoriesByTags", reflect.TypeOf((*MockQuerier)(nil).RecallMemoriesByTags), ctx, arg)
}

// RemoveTransactionLabel mocks base method.
func (m *MockQuerier) RemoveTransactionLabel(ctx context.Context, arg sqlcgen.RemoveTransactionLabelParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTransactionLabel", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTransactionLabel indicates an expected call of RemoveTransactionLabel.
func (mr *MockQuerierMockRecorder) RemoveTransactionLabel(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTransactionLabel", reflect.TypeOf((*MockQuerier)(nil).RemoveTransactionLabel), ctx, arg)
}

// SaveMessage mocks base method.
func (m *MockQuerier) SaveMessage(ctx context.Context, arg sqlcgen.SaveMessageParams) (sqlcgen.ConversationMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.ConversationMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockQuerierMockRecorder) SaveMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockQuerier)(nil).SaveMessage), ctx, arg)
}

// TouchSession mocks base method.
func (m *MockQuerier) TouchSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchSession indicates an expected call of TouchSession.
func (mr *MockQuerierMockRecorder) TouchSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchSession", reflect.TypeOf((*MockQuerier)(nil).TouchSession), ctx, id)
}

// UpdateEnrichment mocks base method.
func (m *MockQuerier) UpdateEnrichment(ctx context.Context, arg sqlcgen.UpdateEnrichmentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnrichment", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnrichment indicates an expected call of UpdateEnrichment.
func (mr *MockQuerierMockRecorder) UpdateEnrichment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnrichment", reflect.TypeOf((*MockQuerier)(nil).UpdateEnrichment), ctx, arg)
}

// UpdateImportRunCounts mocks base method.
func (m *MockQuerier) UpdateImportRunCounts(ctx context.Context, arg sqlcgen.UpdateImportRunCountsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImportRunCounts", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImportRunCounts indicates an expected call of UpdateImportRunCounts.
func (mr *MockQuerierMockRecorder) UpdateImportRunCounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImportRunCounts", reflect.TypeOf((*MockQuerier)(nil).UpdateImportRunCounts), ctx, arg)
}

// UpdateRecurringLastCharged mocks base method.
func (m *MockQuerier) UpdateRecurringLastCharged(ctx context.Context, arg sqlcgen.UpdateRecurringLastChargedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecurringLastCharged", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecurringLastCharged indicates an expected call of UpdateRecurringLastCharged.
func (mr *MockQuerierMockRecorder) UpdateRecurringLastCharged(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecurringLastCharged", reflect.TypeOf((*MockQuerier)(nil).UpdateRecurringLastCharged), ctx, arg)
}

// UpdateSessionTitle mocks base method.
func (m *MockQuerier) UpdateSessionTitle(ctx context.Context, arg sqlcgen.UpdateSessionTitleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionTitle", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionTitle indicates an expected call of UpdateSessionTitle.
func (mr *MockQuerierMockRecorder) UpdateSessionTitle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionTitle", reflect.TypeOf((*MockQuerier)(nil).UpdateSessionTitle), ctx, arg)
}

// UpdateUserDOB mocks base method.
func (m *MockQuerier) UpdateUserDOB(ctx context.Context, arg sqlcgen.UpdateUserDOBParams) (sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserDOB", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserDOB indicates an expected call of UpdateUserDOB.
func (mr *MockQuerierMockRecorder) UpdateUserDOB(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserDOB", reflect.TypeOf((*MockQuerier)(nil).UpdateUserDOB), ctx, arg)
}

// UpdateUserPreferences mocks base method.
func (m *MockQuerier) UpdateUserPreferences(ctx context.Context, arg sqlcgen.UpdateUserPreferencesParams) (sqlcgen.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPreferences", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPreferences indicates an expected call of UpdateUserPreferences.
func (mr *MockQuerierMockRecorder) UpdateUserPreferences(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPreferences", reflect.TypeOf((*MockQuerier)(nil).UpdateUserPreferences), ctx, arg)
}

// UpsertAccountDetails mocks base method.
func (m *MockQuerier) UpsertAccountDetails(ctx context.Context, arg sqlcgen.UpsertAccountDetailsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAccountDetails", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAccountDetails indicates an expected call of UpsertAccountDetails.
func (mr *MockQuerierMockRecorder) UpsertAccountDetails(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAccountDetails", reflect.TypeOf((*MockQuerier)(nil).UpsertAccountDetails), ctx, arg)
}
