// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/pushkaranand/finagent/internal/model"
)

const addAccountMember = `-- name: AddAccountMember :exec
INSERT INTO account_members (account_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (account_id, user_id) DO NOTHING
`

type AddAccountMemberParams struct {
	AccountID uuid.UUID      `json:"account_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Role      MemberRoleEnum `json:"role"`
}

func (q *Queries) AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error {
	_, err := q.db.Exec(ctx, addAccountMember, arg.AccountID, arg.UserID, arg.Role)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (institution, external_account_id, name, account_type, currency, is_active, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, institution, external_account_id, name, account_type, account_class, currency, current_balance, balance_as_of, is_active, metadata, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Institution       string          `json:"institution"`
	ExternalAccountID *string         `json:"external_account_id"`
	Name              string          `json:"name"`
	AccountType       AccountTypeEnum `json:"account_type"`
	Currency          string          `json:"currency"`
	IsActive          bool            `json:"is_active"`
	Metadata          []byte          `json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Institution,
		arg.ExternalAccountID,
		arg.Name,
		arg.AccountType,
		arg.Currency,
		arg.IsActive,
		arg.Metadata,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Institution,
		&i.ExternalAccountID,
		&i.Name,
		&i.AccountType,
		&i.AccountClass,
		&i.Currency,
		&i.CurrentBalance,
		&i.BalanceAsOf,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, institution, external_account_id, name, account_type, account_class, currency, current_balance, balance_as_of, is_active, metadata, created_at, updated_at, deleted_at FROM accounts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Institution,
		&i.ExternalAccountID,
		&i.Name,
		&i.AccountType,
		&i.AccountClass,
		&i.Currency,
		&i.CurrentBalance,
		&i.BalanceAsOf,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountDetails = `-- name: GetAccountDetails :one
SELECT account_id, account_number, ifsc_code, micr_code, swift_code, linked_phone, linked_email, branch_name, branch_address, pan_linked, nominee_name, updated_at FROM account_details WHERE account_id = $1
`

func (q *Queries) GetAccountDetails(ctx context.Context, accountID uuid.UUID) (AccountDetail, error) {
	row := q.db.QueryRow(ctx, getAccountDetails, accountID)
	var i AccountDetail
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.IfscCode,
		&i.MicrCode,
		&i.SwiftCode,
		&i.LinkedPhone,
		&i.LinkedEmail,
		&i.BranchName,
		&i.BranchAddress,
		&i.PanLinked,
		&i.NomineeName,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT a.id, a.institution, a.external_account_id, a.name, a.account_type, a.account_class, a.currency, a.current_balance, a.balance_as_of, a.is_active, a.metadata, a.created_at, a.updated_at, a.deleted_at
FROM accounts a
JOIN account_members am ON am.account_id = a.id
WHERE am.user_id = $1 AND a.deleted_at IS NULL
ORDER BY a.institution, a.name
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Institution,
			&i.ExternalAccountID,
			&i.Name,
			&i.AccountType,
			&i.AccountClass,
			&i.Currency,
			&i.CurrentBalance,
			&i.BalanceAsOf,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET current_balance = $1, balance_as_of = $2, updated_at = NOW()
WHERE id = $3
  AND (balance_as_of IS NULL OR balance_as_of <= $2)
`

type UpdateAccountBalanceParams struct {
	Balance model.Money `json:"balance"`
	AsOf    pgtype.Date `json:"as_of"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Balance, arg.AsOf, arg.ID)
	return err
}

const upsertAccountDetails = `-- name: UpsertAccountDetails :exec
INSERT INTO account_details (
    account_id, account_number, ifsc_code, micr_code, swift_code,
    linked_phone, linked_email, branch_name, branch_address, pan_linked, nominee_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (account_id) DO UPDATE SET
    account_number = EXCLUDED.account_number,
    ifsc_code      = EXCLUDED.ifsc_code,
    micr_code      = EXCLUDED.micr_code,
    swift_code     = EXCLUDED.swift_code,
    linked_phone   = EXCLUDED.linked_phone,
    linked_email   = EXCLUDED.linked_email,
    branch_name    = EXCLUDED.branch_name,
    branch_address = EXCLUDED.branch_address,
    pan_linked     = EXCLUDED.pan_linked,
    nominee_name   = EXCLUDED.nominee_name,
    updated_at     = NOW()
`

type UpsertAccountDetailsParams struct {
	AccountID     uuid.UUID `json:"account_id"`
	AccountNumber *string   `json:"account_number"`
	IfscCode      *string   `json:"ifsc_code"`
	MicrCode      *string   `json:"micr_code"`
	SwiftCode     *string   `json:"swift_code"`
	LinkedPhone   *string   `json:"linked_phone"`
	LinkedEmail   *string   `json:"linked_email"`
	BranchName    *string   `json:"branch_name"`
	BranchAddress *string   `json:"branch_address"`
	PanLinked     *bool     `json:"pan_linked"`
	NomineeName   *string   `json:"nominee_name"`
}

func (q *Queries) UpsertAccountDetails(ctx context.Context, arg UpsertAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, upsertAccountDetails,
		arg.AccountID,
		arg.AccountNumber,
		arg.IfscCode,
		arg.MicrCode,
		arg.SwiftCode,
		arg.LinkedPhone,
		arg.LinkedEmail,
		arg.BranchName,
		arg.BranchAddress,
		arg.PanLinked,
		arg.NomineeName,
	)
	return err
}
