// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, direction, description, parent_id, depth, color, icon, is_system, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Direction,
		&i.Description,
		&i.ParentID,
		&i.Depth,
		&i.Color,
		&i.Icon,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, direction, description, parent_id, depth, color, icon, is_system, created_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Direction,
		&i.Description,
		&i.ParentID,
		&i.Depth,
		&i.Color,
		&i.Icon,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, direction, description, parent_id, depth, color, icon, is_system, created_at FROM categories ORDER BY depth, slug
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Direction,
			&i.Description,
			&i.ParentID,
			&i.Depth,
			&i.Color,
			&i.Icon,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT id, slug, name, direction, description, parent_id, depth, color, icon, is_system, created_at FROM categories WHERE parent_id = $1 ORDER BY slug
`

func (q *Queries) ListSubCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Direction,
			&i.Description,
			&i.ParentID,
			&i.Depth,
			&i.Color,
			&i.Icon,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelCategories = `-- name: ListTopLevelCategories :many
SELECT id, slug, name, direction, description, parent_id, depth, color, icon, is_system, created_at FROM categories WHERE depth = 0 ORDER BY slug
`

func (q *Queries) ListTopLevelCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listTopLevelCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Direction,
			&i.Description,
			&i.ParentID,
			&i.Depth,
			&i.Color,
			&i.Icon,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
