// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO conversation_sessions (user_id, channel, title)
VALUES ($1, $2, $3)
RETURNING id, user_id, channel, title, started_at, last_active, metadata
`

type CreateSessionParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Channel ChannelEnum `json:"channel"`
	Title   *string     `json:"title"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Channel, arg.Title)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.StartedAt,
		&i.LastActive,
		&i.Metadata,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, channel, title, started_at, last_active, metadata FROM conversation_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (ConversationSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ConversationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.StartedAt,
		&i.LastActive,
		&i.Metadata,
	)
	return i, err
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, session_id, role, content, model_used, tool_name, tool_call_id, token_count, metadata, created_at FROM conversation_messages
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ModelUsed,
			&i.ToolName,
			&i.ToolCallID,
			&i.TokenCount,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, channel, title, started_at, last_active, metadata FROM conversation_sessions
WHERE user_id = $1
ORDER BY last_active DESC
LIMIT $2
`

type ListUserSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ConversationSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationSession
	for rows.Next() {
		var i ConversationSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Title,
			&i.StartedAt,
			&i.LastActive,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMessage = `-- name: SaveMessage :one
INSERT INTO conversation_messages (session_id, role, content, model_used, tool_name, tool_call_id, token_count, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, session_id, role, content, model_used, tool_name, tool_call_id, token_count, metadata, created_at
`

type SaveMessageParams struct {
	SessionID  uuid.UUID   `json:"session_id"`
	Role       MsgRoleEnum `json:"role"`
	Content    string      `json:"content"`
	ModelUsed  *string     `json:"model_used"`
	ToolName   *string     `json:"tool_name"`
	ToolCallID *string     `json:"tool_call_id"`
	TokenCount *int32      `json:"token_count"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, saveMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ModelUsed,
		arg.ToolName,
		arg.ToolCallID,
		arg.TokenCount,
		arg.Metadata,
	)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ModelUsed,
		&i.ToolName,
		&i.ToolCallID,
		&i.TokenCount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE conversation_sessions SET last_active = NOW() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE conversation_sessions SET title = $2 WHERE id = $1
`

type UpdateSessionTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title *string   `json:"title"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateSessionTitle, arg.ID, arg.Title)
	return err
}
