// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixed_deposits.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/pushkaranand/finagent/internal/model"
)

const createFixedDeposit = `-- name: CreateFixedDeposit :one
INSERT INTO fixed_deposits (
    user_id, account_id, bank_fd_number,
    principal_amount, interest_rate_bps, tenure_months,
    start_date, maturity_date, expected_maturity_amount,
    interest_payout, auto_renewal_type, renewed_from_id, notes
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13
)
RETURNING id, user_id, account_id, bank_fd_number, principal_amount, interest_rate_bps, tenure_months, start_date, maturity_date, expected_maturity_amount, actual_payout_amount, interest_payout, auto_renewal_type, status, renewed_from_id, notes, created_at, updated_at
`

type CreateFixedDepositParams struct {
	UserID                 uuid.UUID         `json:"user_id"`
	AccountID              uuid.UUID         `json:"account_id"`
	BankFdNumber           *string           `json:"bank_fd_number"`
	PrincipalAmount        model.Money       `json:"principal_amount"`
	InterestRateBps        int16             `json:"interest_rate_bps"`
	TenureMonths           int16             `json:"tenure_months"`
	StartDate              pgtype.Date       `json:"start_date"`
	MaturityDate           pgtype.Date       `json:"maturity_date"`
	ExpectedMaturityAmount model.Money       `json:"expected_maturity_amount"`
	InterestPayout         FdPayoutEnum      `json:"interest_payout"`
	AutoRenewalType        FdRenewalTypeEnum `json:"auto_renewal_type"`
	RenewedFromID          pgtype.UUID       `json:"renewed_from_id"`
	Notes                  *string           `json:"notes"`
}

func (q *Queries) CreateFixedDeposit(ctx context.Context, arg CreateFixedDepositParams) (FixedDeposit, error) {
	row := q.db.QueryRow(ctx, createFixedDeposit,
		arg.UserID,
		arg.AccountID,
		arg.BankFdNumber,
		arg.PrincipalAmount,
		arg.InterestRateBps,
		arg.TenureMonths,
		arg.StartDate,
		arg.MaturityDate,
		arg.ExpectedMaturityAmount,
		arg.InterestPayout,
		arg.AutoRenewalType,
		arg.RenewedFromID,
		arg.Notes,
	)
	var i FixedDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.BankFdNumber,
		&i.PrincipalAmount,
		&i.InterestRateBps,
		&i.TenureMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.ExpectedMaturityAmount,
		&i.ActualPayoutAmount,
		&i.InterestPayout,
		&i.AutoRenewalType,
		&i.Status,
		&i.RenewedFromID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFixedDeposit = `-- name: GetFixedDeposit :one
SELECT id, user_id, account_id, bank_fd_number, principal_amount, interest_rate_bps, tenure_months, start_date, maturity_date, expected_maturity_amount, actual_payout_amount, interest_payout, auto_renewal_type, status, renewed_from_id, notes, created_at, updated_at FROM fixed_deposits WHERE id = $1 AND user_id = $2
`

type GetFixedDepositParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFixedDeposit(ctx context.Context, arg GetFixedDepositParams) (FixedDeposit, error) {
	row := q.db.QueryRow(ctx, getFixedDeposit, arg.ID, arg.UserID)
	var i FixedDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.BankFdNumber,
		&i.PrincipalAmount,
		&i.InterestRateBps,
		&i.TenureMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.ExpectedMaturityAmount,
		&i.ActualPayoutAmount,
		&i.InterestPayout,
		&i.AutoRenewalType,
		&i.Status,
		&i.RenewedFromID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFixedDeposits = `-- name: ListFixedDeposits :many
SELECT id, user_id, account_id, bank_fd_number, principal_amount, interest_rate_bps, tenure_months, start_date, maturity_date, expected_maturity_amount, actual_payout_amount, interest_payout, auto_renewal_type, status, renewed_from_id, notes, created_at, updated_at FROM fixed_deposits
WHERE user_id = $1
  AND ($2::fd_status_enum IS NULL OR status = $2::fd_status_enum)
  AND ($3::date IS NULL OR maturity_date <= $3::date)
ORDER BY maturity_date ASC
`

type ListFixedDepositsParams struct {
	UserID         uuid.UUID     `json:"user_id"`
	Status         *FdStatusEnum `json:"status"`
	MaturingBefore pgtype.Date   `json:"maturing_before"`
}

func (q *Queries) ListFixedDeposits(ctx context.Context, arg ListFixedDepositsParams) ([]FixedDeposit, error) {
	rows, err := q.db.Query(ctx, listFixedDeposits, arg.UserID, arg.Status, arg.MaturingBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedDeposit
	for rows.Next() {
		var i FixedDeposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.BankFdNumber,
			&i.PrincipalAmount,
			&i.InterestRateBps,
			&i.TenureMonths,
			&i.StartDate,
			&i.MaturityDate,
			&i.ExpectedMaturityAmount,
			&i.ActualPayoutAmount,
			&i.InterestPayout,
			&i.AutoRenewalType,
			&i.Status,
			&i.RenewedFromID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixedDepositStatus = `-- name: UpdateFixedDepositStatus :one
UPDATE fixed_deposits
SET status               = $1,
    actual_payout_amount = $2,
    updated_at           = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, account_id, bank_fd_number, principal_amount, interest_rate_bps, tenure_months, start_date, maturity_date, expected_maturity_amount, actual_payout_amount, interest_payout, auto_renewal_type, status, renewed_from_id, notes, created_at, updated_at
`

type UpdateFixedDepositStatusParams struct {
	Status             FdStatusEnum `json:"status"`
	ActualPayoutAmount model.Money  `json:"actual_payout_amount"`
	ID                 uuid.UUID    `json:"id"`
	UserID             uuid.UUID    `json:"user_id"`
}

func (q *Queries) UpdateFixedDepositStatus(ctx context.Context, arg UpdateFixedDepositStatusParams) (FixedDeposit, error) {
	row := q.db.QueryRow(ctx, updateFixedDepositStatus,
		arg.Status,
		arg.ActualPayoutAmount,
		arg.ID,
		arg.UserID,
	)
	var i FixedDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.BankFdNumber,
		&i.PrincipalAmount,
		&i.InterestRateBps,
		&i.TenureMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.ExpectedMaturityAmount,
		&i.ActualPayoutAmount,
		&i.InterestPayout,
		&i.AutoRenewalType,
		&i.Status,
		&i.RenewedFromID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
