// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_runs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createImportRun = `-- name: CreateImportRun :one
INSERT INTO import_runs (user_id, account_id, provider, source_ref, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, account_id, provider, status, source_ref, rows_parsed, rows_inserted, rows_duplicate, rows_failed, error_detail, started_at, finished_at, metadata
`

type CreateImportRunParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Provider  ImportProviderEnum `json:"provider"`
	SourceRef *string            `json:"source_ref"`
	Metadata  []byte             `json:"metadata"`
}

func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error) {
	row := q.db.QueryRow(ctx, createImportRun,
		arg.UserID,
		arg.AccountID,
		arg.Provider,
		arg.SourceRef,
		arg.Metadata,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Provider,
		&i.Status,
		&i.SourceRef,
		&i.RowsParsed,
		&i.RowsInserted,
		&i.RowsDuplicate,
		&i.RowsFailed,
		&i.ErrorDetail,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Metadata,
	)
	return i, err
}

const finishImportRun = `-- name: FinishImportRun :exec
UPDATE import_runs
SET status       = $1,
    finished_at  = NOW(),
    error_detail = $2
WHERE id = $3
`

type FinishImportRunParams struct {
	Status      ImportStatusEnum `json:"status"`
	ErrorDetail *string          `json:"error_detail"`
	ID          uuid.UUID        `json:"id"`
}

func (q *Queries) FinishImportRun(ctx context.Context, arg FinishImportRunParams) error {
	_, err := q.db.Exec(ctx, finishImportRun, arg.Status, arg.ErrorDetail, arg.ID)
	return err
}

const listImportRuns = `-- name: ListImportRuns :many
SELECT id, user_id, account_id, provider, status, source_ref, rows_parsed, rows_inserted, rows_duplicate, rows_failed, error_detail, started_at, finished_at, metadata FROM import_runs WHERE user_id = $1 ORDER BY started_at DESC LIMIT 20
`

func (q *Queries) ListImportRuns(ctx context.Context, userID uuid.UUID) ([]ImportRun, error) {
	rows, err := q.db.Query(ctx, listImportRuns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportRun
	for rows.Next() {
		var i ImportRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Provider,
			&i.Status,
			&i.SourceRef,
			&i.RowsParsed,
			&i.RowsInserted,
			&i.RowsDuplicate,
			&i.RowsFailed,
			&i.ErrorDetail,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportRunCounts = `-- name: UpdateImportRunCounts :exec
UPDATE import_runs
SET rows_parsed    = $1,
    rows_inserted  = $2,
    rows_duplicate = $3,
    rows_failed    = $4
WHERE id = $5
`

type UpdateImportRunCountsParams struct {
	RowsParsed    int32     `json:"rows_parsed"`
	RowsInserted  int32     `json:"rows_inserted"`
	RowsDuplicate int32     `json:"rows_duplicate"`
	RowsFailed    int32     `json:"rows_failed"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateImportRunCounts(ctx context.Context, arg UpdateImportRunCountsParams) error {
	_, err := q.db.Exec(ctx, updateImportRunCounts,
		arg.RowsParsed,
		arg.RowsInserted,
		arg.RowsDuplicate,
		arg.RowsFailed,
		arg.ID,
	)
	return err
}
