// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTransactionLabel = `-- name: AddTransactionLabel :exec
INSERT INTO transaction_labels (transaction_id, label_id, source)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddTransactionLabelParams struct {
	TransactionID uuid.UUID           `json:"transaction_id"`
	LabelID       uuid.UUID           `json:"label_id"`
	Source        DetectionSourceEnum `json:"source"`
}

func (q *Queries) AddTransactionLabel(ctx context.Context, arg AddTransactionLabelParams) error {
	_, err := q.db.Exec(ctx, addTransactionLabel, arg.TransactionID, arg.LabelID, arg.Source)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (user_id, name, slug, color)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, slug, color, created_at
`

type CreateLabelParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Slug   string      `json:"slug"`
	Color  *string     `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Color,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getLabelBySlug = `-- name: GetLabelBySlug :one
SELECT id, user_id, name, slug, color, created_at FROM labels WHERE slug = $1
`

func (q *Queries) GetLabelBySlug(ctx context.Context, slug string) (Label, error) {
	row := q.db.QueryRow(ctx, getLabelBySlug, slug)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, user_id, name, slug, color, created_at FROM labels WHERE user_id = $1 OR user_id IS NULL ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, userID pgtype.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionLabels = `-- name: ListTransactionLabels :many
SELECT l.id, l.user_id, l.name, l.slug, l.color, l.created_at FROM labels l
JOIN transaction_labels tl ON tl.label_id = l.id
WHERE tl.transaction_id = $1
`

func (q *Queries) ListTransactionLabels(ctx context.Context, transactionID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listTransactionLabels, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTransactionLabel = `-- name: RemoveTransactionLabel :exec
DELETE FROM transaction_labels WHERE transaction_id = $1 AND label_id = $2
`

type RemoveTransactionLabelParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	LabelID       uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveTransactionLabel(ctx context.Context, arg RemoveTransactionLabelParams) error {
	_, err := q.db.Exec(ctx, removeTransactionLabel, arg.TransactionID, arg.LabelID)
	return err
}
