// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO agent_memories (user_id, content, memory_type, detection_source, tags, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, content, memory_type, detection_source, tags, embedding, expires_at, is_active, created_at, updated_at
`

type CreateMemoryParams struct {
	UserID          pgtype.UUID         `json:"user_id"`
	Content         string              `json:"content"`
	MemoryType      MemoryTypeEnum      `json:"memory_type"`
	DetectionSource DetectionSourceEnum `json:"detection_source"`
	Tags            []string            `json:"tags"`
	ExpiresAt       pgtype.Timestamptz  `json:"expires_at"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.UserID,
		arg.Content,
		arg.MemoryType,
		arg.DetectionSource,
		arg.Tags,
		arg.ExpiresAt,
	)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.MemoryType,
		&i.DetectionSource,
		&i.Tags,
		&i.Embedding,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMemory = `-- name: DeactivateMemory :exec
UPDATE agent_memories SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateMemory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateMemory, id)
	return err
}

const listMemories = `-- name: ListMemories :many
SELECT id, user_id, content, memory_type, detection_source, tags, embedding, expires_at, is_active, created_at, updated_at FROM agent_memories
WHERE is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
  AND (user_id = $1 OR user_id IS NULL)
ORDER BY created_at DESC
LIMIT $2
`

type ListMemoriesParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, listMemories, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMemory
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.MemoryType,
			&i.DetectionSource,
			&i.Tags,
			&i.Embedding,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMemoriesByTags = `-- name: RecallMemoriesByTags :many
SELECT id, user_id, content, memory_type, detection_source, tags, embedding, expires_at, is_active, created_at, updated_at FROM agent_memories
WHERE is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
  AND (user_id = $1 OR user_id IS NULL)
  AND (tags = '{}' OR tags && $2)
ORDER BY created_at DESC
LIMIT $3
`

type RecallMemoriesByTagsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Tags      []string    `json:"tags"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) RecallMemoriesByTags(ctx context.Context, arg RecallMemoriesByTagsParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, recallMemoriesByTags, arg.UserID, arg.Tags, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMemory
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.MemoryType,
			&i.DetectionSource,
			&i.Tags,
			&i.Embedding,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
