// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
	model "github.com/pushkaranand/finagent/internal/model"
)

type AccountClassEnum string

const (
	AccountClassEnumAsset     AccountClassEnum = "asset"
	AccountClassEnumLiability AccountClassEnum = "liability"
)

func (e *AccountClassEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountClassEnum(s)
	case string:
		*e = AccountClassEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountClassEnum: %T", src)
	}
	return nil
}

type NullAccountClassEnum struct {
	AccountClassEnum AccountClassEnum `json:"account_class_enum"`
	Valid            bool             `json:"valid"` // Valid is true if AccountClassEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountClassEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AccountClassEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountClassEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountClassEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountClassEnum), nil
}

func (e AccountClassEnum) Valid() bool {
	switch e {
	case AccountClassEnumAsset,
		AccountClassEnumLiability:
		return true
	}
	return false
}

func AllAccountClassEnumValues() []AccountClassEnum {
	return []AccountClassEnum{
		AccountClassEnumAsset,
		AccountClassEnumLiability,
	}
}

type AccountTypeEnum string

const (
	AccountTypeEnumBankSavings AccountTypeEnum = "bank_savings"
	AccountTypeEnumBankCurrent AccountTypeEnum = "bank_current"
	AccountTypeEnumBankSalary  AccountTypeEnum = "bank_salary"
	AccountTypeEnumCreditCard  AccountTypeEnum = "credit_card"
	AccountTypeEnumLoan        AccountTypeEnum = "loan"
	AccountTypeEnumMortgage    AccountTypeEnum = "mortgage"
	AccountTypeEnumDemat       AccountTypeEnum = "demat"
	AccountTypeEnumBrokerage   AccountTypeEnum = "brokerage"
	AccountTypeEnumPpf         AccountTypeEnum = "ppf"
	AccountTypeEnumEpf         AccountTypeEnum = "epf"
	AccountTypeEnumNps         AccountTypeEnum = "nps"
	AccountTypeEnumFd          AccountTypeEnum = "fd"
	AccountTypeEnumCrypto      AccountTypeEnum = "crypto"
	AccountTypeEnumWallet      AccountTypeEnum = "wallet"
)

func (e *AccountTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountTypeEnum(s)
	case string:
		*e = AccountTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountTypeEnum: %T", src)
	}
	return nil
}

type NullAccountTypeEnum struct {
	AccountTypeEnum AccountTypeEnum `json:"account_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if AccountTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AccountTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountTypeEnum), nil
}

func (e AccountTypeEnum) Valid() bool {
	switch e {
	case AccountTypeEnumBankSavings,
		AccountTypeEnumBankCurrent,
		AccountTypeEnumBankSalary,
		AccountTypeEnumCreditCard,
		AccountTypeEnumLoan,
		AccountTypeEnumMortgage,
		AccountTypeEnumDemat,
		AccountTypeEnumBrokerage,
		AccountTypeEnumPpf,
		AccountTypeEnumEpf,
		AccountTypeEnumNps,
		AccountTypeEnumFd,
		AccountTypeEnumCrypto,
		AccountTypeEnumWallet:
		return true
	}
	return false
}

func AllAccountTypeEnumValues() []AccountTypeEnum {
	return []AccountTypeEnum{
		AccountTypeEnumBankSavings,
		AccountTypeEnumBankCurrent,
		AccountTypeEnumBankSalary,
		AccountTypeEnumCreditCard,
		AccountTypeEnumLoan,
		AccountTypeEnumMortgage,
		AccountTypeEnumDemat,
		AccountTypeEnumBrokerage,
		AccountTypeEnumPpf,
		AccountTypeEnumEpf,
		AccountTypeEnumNps,
		AccountTypeEnumFd,
		AccountTypeEnumCrypto,
		AccountTypeEnumWallet,
	}
}

type ChannelEnum string

const (
	ChannelEnumCli    ChannelEnum = "cli"
	ChannelEnumSlack  ChannelEnum = "slack"
	ChannelEnumSignal ChannelEnum = "signal"
	ChannelEnumApi    ChannelEnum = "api"
)

func (e *ChannelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelEnum(s)
	case string:
		*e = ChannelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelEnum: %T", src)
	}
	return nil
}

type NullChannelEnum struct {
	ChannelEnum ChannelEnum `json:"channel_enum"`
	Valid       bool        `json:"valid"` // Valid is true if ChannelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelEnum), nil
}

func (e ChannelEnum) Valid() bool {
	switch e {
	case ChannelEnumCli,
		ChannelEnumSlack,
		ChannelEnumSignal,
		ChannelEnumApi:
		return true
	}
	return false
}

func AllChannelEnumValues() []ChannelEnum {
	return []ChannelEnum{
		ChannelEnumCli,
		ChannelEnumSlack,
		ChannelEnumSignal,
		ChannelEnumApi,
	}
}

type DetectionSourceEnum string

const (
	DetectionSourceEnumLlm  DetectionSourceEnum = "llm"
	DetectionSourceEnumUser DetectionSourceEnum = "user"
	DetectionSourceEnumRule DetectionSourceEnum = "rule"
)

func (e *DetectionSourceEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DetectionSourceEnum(s)
	case string:
		*e = DetectionSourceEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DetectionSourceEnum: %T", src)
	}
	return nil
}

type NullDetectionSourceEnum struct {
	DetectionSourceEnum DetectionSourceEnum `json:"detection_source_enum"`
	Valid               bool                `json:"valid"` // Valid is true if DetectionSourceEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDetectionSourceEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DetectionSourceEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DetectionSourceEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDetectionSourceEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DetectionSourceEnum), nil
}

func (e DetectionSourceEnum) Valid() bool {
	switch e {
	case DetectionSourceEnumLlm,
		DetectionSourceEnumUser,
		DetectionSourceEnumRule:
		return true
	}
	return false
}

func AllDetectionSourceEnumValues() []DetectionSourceEnum {
	return []DetectionSourceEnum{
		DetectionSourceEnumLlm,
		DetectionSourceEnumUser,
		DetectionSourceEnumRule,
	}
}

type FrequencyEnum string

const (
	FrequencyEnumDaily     FrequencyEnum = "daily"
	FrequencyEnumWeekly    FrequencyEnum = "weekly"
	FrequencyEnumMonthly   FrequencyEnum = "monthly"
	FrequencyEnumQuarterly FrequencyEnum = "quarterly"
	FrequencyEnumAnnual    FrequencyEnum = "annual"
)

func (e *FrequencyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrequencyEnum(s)
	case string:
		*e = FrequencyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for FrequencyEnum: %T", src)
	}
	return nil
}

type NullFrequencyEnum struct {
	FrequencyEnum FrequencyEnum `json:"frequency_enum"`
	Valid         bool          `json:"valid"` // Valid is true if FrequencyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequencyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.FrequencyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrequencyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequencyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrequencyEnum), nil
}

func (e FrequencyEnum) Valid() bool {
	switch e {
	case FrequencyEnumDaily,
		FrequencyEnumWeekly,
		FrequencyEnumMonthly,
		FrequencyEnumQuarterly,
		FrequencyEnumAnnual:
		return true
	}
	return false
}

func AllFrequencyEnumValues() []FrequencyEnum {
	return []FrequencyEnum{
		FrequencyEnumDaily,
		FrequencyEnumWeekly,
		FrequencyEnumMonthly,
		FrequencyEnumQuarterly,
		FrequencyEnumAnnual,
	}
}

type ImportProviderEnum string

const (
	ImportProviderEnumCsv     ImportProviderEnum = "csv"
	ImportProviderEnumZerodha ImportProviderEnum = "zerodha"
	ImportProviderEnumManual  ImportProviderEnum = "manual"
)

func (e *ImportProviderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportProviderEnum(s)
	case string:
		*e = ImportProviderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportProviderEnum: %T", src)
	}
	return nil
}

type NullImportProviderEnum struct {
	ImportProviderEnum ImportProviderEnum `json:"import_provider_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ImportProviderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportProviderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ImportProviderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportProviderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportProviderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportProviderEnum), nil
}

func (e ImportProviderEnum) Valid() bool {
	switch e {
	case ImportProviderEnumCsv,
		ImportProviderEnumZerodha,
		ImportProviderEnumManual:
		return true
	}
	return false
}

func AllImportProviderEnumValues() []ImportProviderEnum {
	return []ImportProviderEnum{
		ImportProviderEnumCsv,
		ImportProviderEnumZerodha,
		ImportProviderEnumManual,
	}
}

type ImportStatusEnum string

const (
	ImportStatusEnumRunning ImportStatusEnum = "running"
	ImportStatusEnumSuccess ImportStatusEnum = "success"
	ImportStatusEnumPartial ImportStatusEnum = "partial"
	ImportStatusEnumFailed  ImportStatusEnum = "failed"
)

func (e *ImportStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatusEnum(s)
	case string:
		*e = ImportStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatusEnum: %T", src)
	}
	return nil
}

type NullImportStatusEnum struct {
	ImportStatusEnum ImportStatusEnum `json:"import_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ImportStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatusEnum), nil
}

func (e ImportStatusEnum) Valid() bool {
	switch e {
	case ImportStatusEnumRunning,
		ImportStatusEnumSuccess,
		ImportStatusEnumPartial,
		ImportStatusEnumFailed:
		return true
	}
	return false
}

func AllImportStatusEnumValues() []ImportStatusEnum {
	return []ImportStatusEnum{
		ImportStatusEnumRunning,
		ImportStatusEnumSuccess,
		ImportStatusEnumPartial,
		ImportStatusEnumFailed,
	}
}

type MemberRoleEnum string

const (
	MemberRoleEnumOwner MemberRoleEnum = "owner"
	MemberRoleEnumJoint MemberRoleEnum = "joint"
)

func (e *MemberRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRoleEnum(s)
	case string:
		*e = MemberRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRoleEnum: %T", src)
	}
	return nil
}

type NullMemberRoleEnum struct {
	MemberRoleEnum MemberRoleEnum `json:"member_role_enum"`
	Valid          bool           `json:"valid"` // Valid is true if MemberRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRoleEnum), nil
}

func (e MemberRoleEnum) Valid() bool {
	switch e {
	case MemberRoleEnumOwner,
		MemberRoleEnumJoint:
		return true
	}
	return false
}

func AllMemberRoleEnumValues() []MemberRoleEnum {
	return []MemberRoleEnum{
		MemberRoleEnumOwner,
		MemberRoleEnumJoint,
	}
}

type MemoryTypeEnum string

const (
	MemoryTypeEnumGeneral       MemoryTypeEnum = "general"
	MemoryTypeEnumTaggingHint   MemoryTypeEnum = "tagging_hint"
	MemoryTypeEnumRecurringHint MemoryTypeEnum = "recurring_hint"
	MemoryTypeEnumPreference    MemoryTypeEnum = "preference"
)

func (e *MemoryTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemoryTypeEnum(s)
	case string:
		*e = MemoryTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MemoryTypeEnum: %T", src)
	}
	return nil
}

type NullMemoryTypeEnum struct {
	MemoryTypeEnum MemoryTypeEnum `json:"memory_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if MemoryTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemoryTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MemoryTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemoryTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemoryTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemoryTypeEnum), nil
}

func (e MemoryTypeEnum) Valid() bool {
	switch e {
	case MemoryTypeEnumGeneral,
		MemoryTypeEnumTaggingHint,
		MemoryTypeEnumRecurringHint,
		MemoryTypeEnumPreference:
		return true
	}
	return false
}

func AllMemoryTypeEnumValues() []MemoryTypeEnum {
	return []MemoryTypeEnum{
		MemoryTypeEnumGeneral,
		MemoryTypeEnumTaggingHint,
		MemoryTypeEnumRecurringHint,
		MemoryTypeEnumPreference,
	}
}

type MsgRoleEnum string

const (
	MsgRoleEnumSystem    MsgRoleEnum = "system"
	MsgRoleEnumUser      MsgRoleEnum = "user"
	MsgRoleEnumAssistant MsgRoleEnum = "assistant"
	MsgRoleEnumTool      MsgRoleEnum = "tool"
)

func (e *MsgRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsgRoleEnum(s)
	case string:
		*e = MsgRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MsgRoleEnum: %T", src)
	}
	return nil
}

type NullMsgRoleEnum struct {
	MsgRoleEnum MsgRoleEnum `json:"msg_role_enum"`
	Valid       bool        `json:"valid"` // Valid is true if MsgRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsgRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MsgRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsgRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsgRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsgRoleEnum), nil
}

func (e MsgRoleEnum) Valid() bool {
	switch e {
	case MsgRoleEnumSystem,
		MsgRoleEnumUser,
		MsgRoleEnumAssistant,
		MsgRoleEnumTool:
		return true
	}
	return false
}

func AllMsgRoleEnumValues() []MsgRoleEnum {
	return []MsgRoleEnum{
		MsgRoleEnumSystem,
		MsgRoleEnumUser,
		MsgRoleEnumAssistant,
		MsgRoleEnumTool,
	}
}

type PaymentModeEnum string

const (
	PaymentModeEnumUpi        PaymentModeEnum = "upi"
	PaymentModeEnumNeft       PaymentModeEnum = "neft"
	PaymentModeEnumRtgs       PaymentModeEnum = "rtgs"
	PaymentModeEnumImps       PaymentModeEnum = "imps"
	PaymentModeEnumNach       PaymentModeEnum = "nach"
	PaymentModeEnumCheque     PaymentModeEnum = "cheque"
	PaymentModeEnumAtm        PaymentModeEnum = "atm"
	PaymentModeEnumPos        PaymentModeEnum = "pos"
	PaymentModeEnumEmi        PaymentModeEnum = "emi"
	PaymentModeEnumOnline     PaymentModeEnum = "online"
	PaymentModeEnumUpiAutopay PaymentModeEnum = "upi_autopay"
)

func (e *PaymentModeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentModeEnum(s)
	case string:
		*e = PaymentModeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentModeEnum: %T", src)
	}
	return nil
}

type NullPaymentModeEnum struct {
	PaymentModeEnum PaymentModeEnum `json:"payment_mode_enum"`
	Valid           bool            `json:"valid"` // Valid is true if PaymentModeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentModeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentModeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentModeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentModeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentModeEnum), nil
}

func (e PaymentModeEnum) Valid() bool {
	switch e {
	case PaymentModeEnumUpi,
		PaymentModeEnumNeft,
		PaymentModeEnumRtgs,
		PaymentModeEnumImps,
		PaymentModeEnumNach,
		PaymentModeEnumCheque,
		PaymentModeEnumAtm,
		PaymentModeEnumPos,
		PaymentModeEnumEmi,
		PaymentModeEnumOnline,
		PaymentModeEnumUpiAutopay:
		return true
	}
	return false
}

func AllPaymentModeEnumValues() []PaymentModeEnum {
	return []PaymentModeEnum{
		PaymentModeEnumUpi,
		PaymentModeEnumNeft,
		PaymentModeEnumRtgs,
		PaymentModeEnumImps,
		PaymentModeEnumNach,
		PaymentModeEnumCheque,
		PaymentModeEnumAtm,
		PaymentModeEnumPos,
		PaymentModeEnumEmi,
		PaymentModeEnumOnline,
		PaymentModeEnumUpiAutopay,
	}
}

type PhysicalAssetTypeEnum string

const (
	PhysicalAssetTypeEnumVehicle      PhysicalAssetTypeEnum = "vehicle"
	PhysicalAssetTypeEnumJewellery    PhysicalAssetTypeEnum = "jewellery"
	PhysicalAssetTypeEnumRealEstate   PhysicalAssetTypeEnum = "real_estate"
	PhysicalAssetTypeEnumPhysicalGold PhysicalAssetTypeEnum = "physical_gold"
	PhysicalAssetTypeEnumOther        PhysicalAssetTypeEnum = "other"
)

func (e *PhysicalAssetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhysicalAssetTypeEnum(s)
	case string:
		*e = PhysicalAssetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PhysicalAssetTypeEnum: %T", src)
	}
	return nil
}

type NullPhysicalAssetTypeEnum struct {
	PhysicalAssetTypeEnum PhysicalAssetTypeEnum `json:"physical_asset_type_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if PhysicalAssetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhysicalAssetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PhysicalAssetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhysicalAssetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhysicalAssetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhysicalAssetTypeEnum), nil
}

func (e PhysicalAssetTypeEnum) Valid() bool {
	switch e {
	case PhysicalAssetTypeEnumVehicle,
		PhysicalAssetTypeEnumJewellery,
		PhysicalAssetTypeEnumRealEstate,
		PhysicalAssetTypeEnumPhysicalGold,
		PhysicalAssetTypeEnumOther:
		return true
	}
	return false
}

func AllPhysicalAssetTypeEnumValues() []PhysicalAssetTypeEnum {
	return []PhysicalAssetTypeEnum{
		PhysicalAssetTypeEnumVehicle,
		PhysicalAssetTypeEnumJewellery,
		PhysicalAssetTypeEnumRealEstate,
		PhysicalAssetTypeEnumPhysicalGold,
		PhysicalAssetTypeEnumOther,
	}
}

type RecurringModeEnum string

const (
	RecurringModeEnumNach                RecurringModeEnum = "nach"
	RecurringModeEnumUpiAutopay          RecurringModeEnum = "upi_autopay"
	RecurringModeEnumCcCharge            RecurringModeEnum = "cc_charge"
	RecurringModeEnumStandingInstruction RecurringModeEnum = "standing_instruction"
	RecurringModeEnumUnknown             RecurringModeEnum = "unknown"
)

func (e *RecurringModeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurringModeEnum(s)
	case string:
		*e = RecurringModeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurringModeEnum: %T", src)
	}
	return nil
}

type NullRecurringModeEnum struct {
	RecurringModeEnum RecurringModeEnum `json:"recurring_mode_enum"`
	Valid             bool              `json:"valid"` // Valid is true if RecurringModeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurringModeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RecurringModeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurringModeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurringModeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurringModeEnum), nil
}

func (e RecurringModeEnum) Valid() bool {
	switch e {
	case RecurringModeEnumNach,
		RecurringModeEnumUpiAutopay,
		RecurringModeEnumCcCharge,
		RecurringModeEnumStandingInstruction,
		RecurringModeEnumUnknown:
		return true
	}
	return false
}

func AllRecurringModeEnumValues() []RecurringModeEnum {
	return []RecurringModeEnum{
		RecurringModeEnumNach,
		RecurringModeEnumUpiAutopay,
		RecurringModeEnumCcCharge,
		RecurringModeEnumStandingInstruction,
		RecurringModeEnumUnknown,
	}
}

type TaggingStatusEnum string

const (
	TaggingStatusEnumPending TaggingStatusEnum = "pending"
	TaggingStatusEnumAuto    TaggingStatusEnum = "auto"
	TaggingStatusEnumManual  TaggingStatusEnum = "manual"
)

func (e *TaggingStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaggingStatusEnum(s)
	case string:
		*e = TaggingStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TaggingStatusEnum: %T", src)
	}
	return nil
}

type NullTaggingStatusEnum struct {
	TaggingStatusEnum TaggingStatusEnum `json:"tagging_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if TaggingStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaggingStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TaggingStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaggingStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaggingStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaggingStatusEnum), nil
}

func (e TaggingStatusEnum) Valid() bool {
	switch e {
	case TaggingStatusEnumPending,
		TaggingStatusEnumAuto,
		TaggingStatusEnumManual:
		return true
	}
	return false
}

func AllTaggingStatusEnumValues() []TaggingStatusEnum {
	return []TaggingStatusEnum{
		TaggingStatusEnumPending,
		TaggingStatusEnumAuto,
		TaggingStatusEnumManual,
	}
}

type TransferTypeEnum string

const (
	TransferTypeEnumOwn        TransferTypeEnum = "own"
	TransferTypeEnumHousehold  TransferTypeEnum = "household"
	TransferTypeEnumInvestment TransferTypeEnum = "investment"
)

func (e *TransferTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferTypeEnum(s)
	case string:
		*e = TransferTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferTypeEnum: %T", src)
	}
	return nil
}

type NullTransferTypeEnum struct {
	TransferTypeEnum TransferTypeEnum `json:"transfer_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if TransferTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransferTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferTypeEnum), nil
}

func (e TransferTypeEnum) Valid() bool {
	switch e {
	case TransferTypeEnumOwn,
		TransferTypeEnumHousehold,
		TransferTypeEnumInvestment:
		return true
	}
	return false
}

func AllTransferTypeEnumValues() []TransferTypeEnum {
	return []TransferTypeEnum{
		TransferTypeEnumOwn,
		TransferTypeEnumHousehold,
		TransferTypeEnumInvestment,
	}
}

type TxnDirectionEnum string

const (
	TxnDirectionEnumDebit  TxnDirectionEnum = "debit"
	TxnDirectionEnumCredit TxnDirectionEnum = "credit"
	TxnDirectionEnumBoth   TxnDirectionEnum = "both"
)

func (e *TxnDirectionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxnDirectionEnum(s)
	case string:
		*e = TxnDirectionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TxnDirectionEnum: %T", src)
	}
	return nil
}

type NullTxnDirectionEnum struct {
	TxnDirectionEnum TxnDirectionEnum `json:"txn_direction_enum"`
	Valid            bool             `json:"valid"` // Valid is true if TxnDirectionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxnDirectionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TxnDirectionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxnDirectionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxnDirectionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxnDirectionEnum), nil
}

func (e TxnDirectionEnum) Valid() bool {
	switch e {
	case TxnDirectionEnumDebit,
		TxnDirectionEnumCredit,
		TxnDirectionEnumBoth:
		return true
	}
	return false
}

func AllTxnDirectionEnumValues() []TxnDirectionEnum {
	return []TxnDirectionEnum{
		TxnDirectionEnumDebit,
		TxnDirectionEnumCredit,
		TxnDirectionEnumBoth,
	}
}

type Account struct {
	ID                uuid.UUID          `json:"id"`
	Institution       string             `json:"institution"`
	ExternalAccountID *string            `json:"external_account_id"`
	Name              string             `json:"name"`
	AccountType       AccountTypeEnum    `json:"account_type"`
	AccountClass      AccountClassEnum   `json:"account_class"`
	Currency          string             `json:"currency"`
	IsActive          bool               `json:"is_active"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type AccountDetail struct {
	AccountID     uuid.UUID          `json:"account_id"`
	AccountNumber *string            `json:"account_number"`
	IfscCode      *string            `json:"ifsc_code"`
	MicrCode      *string            `json:"micr_code"`
	SwiftCode     *string            `json:"swift_code"`
	LinkedPhone   *string            `json:"linked_phone"`
	LinkedEmail   *string            `json:"linked_email"`
	BranchName    *string            `json:"branch_name"`
	BranchAddress *string            `json:"branch_address"`
	PanLinked     *bool              `json:"pan_linked"`
	NomineeName   *string            `json:"nominee_name"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AccountMember struct {
	AccountID uuid.UUID      `json:"account_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Role      MemberRoleEnum `json:"role"`
}

type AgentMemory struct {
	ID              uuid.UUID           `json:"id"`
	UserID          pgtype.UUID         `json:"user_id"`
	Content         string              `json:"content"`
	MemoryType      MemoryTypeEnum      `json:"memory_type"`
	DetectionSource DetectionSourceEnum `json:"detection_source"`
	Tags            []string            `json:"tags"`
	Embedding       *pgvector.Vector    `json:"embedding"`
	ExpiresAt       pgtype.Timestamptz  `json:"expires_at"`
	IsActive        bool                `json:"is_active"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz  `json:"updated_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Direction   TxnDirectionEnum   `json:"direction"`
	Description string             `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Depth       int16              `json:"depth"`
	Color       *string            `json:"color"`
	Icon        *string            `json:"icon"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConversationMessage struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	Role       MsgRoleEnum        `json:"role"`
	Content    string             `json:"content"`
	ModelUsed  *string            `json:"model_used"`
	ToolName   *string            `json:"tool_name"`
	ToolCallID *string            `json:"tool_call_id"`
	TokenCount *int32             `json:"token_count"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ConversationSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Channel    ChannelEnum        `json:"channel"`
	Title      *string            `json:"title"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	LastActive pgtype.Timestamptz `json:"last_active"`
	Metadata   []byte             `json:"metadata"`
}

type ImportRun struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Provider      ImportProviderEnum `json:"provider"`
	Status        ImportStatusEnum   `json:"status"`
	SourceRef     *string            `json:"source_ref"`
	RowsParsed    int32              `json:"rows_parsed"`
	RowsInserted  int32              `json:"rows_inserted"`
	RowsDuplicate int32              `json:"rows_duplicate"`
	RowsFailed    int32              `json:"rows_failed"`
	ErrorDetail   *string            `json:"error_detail"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Metadata      []byte             `json:"metadata"`
}

type Label struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Color     *string            `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecurringPayment struct {
	ID                     uuid.UUID           `json:"id"`
	UserID                 uuid.UUID           `json:"user_id"`
	AccountID              uuid.UUID           `json:"account_id"`
	Name                   string              `json:"name"`
	CategoryID             pgtype.UUID         `json:"category_id"`
	ExpectedAmount         model.Money         `json:"expected_amount"`
	AmountVariance         model.Money         `json:"amount_variance"`
	Frequency              FrequencyEnum       `json:"frequency"`
	ApproximateDay         *int16              `json:"approximate_day"`
	PaymentMode            *RecurringModeEnum  `json:"payment_mode"`
	CounterpartyIdentifier *string             `json:"counterparty_identifier"`
	CounterpartyName       *string             `json:"counterparty_name"`
	DetectionSource        DetectionSourceEnum `json:"detection_source"`
	IsActive               bool                `json:"is_active"`
	LastChargedAt          pgtype.Date         `json:"last_charged_at"`
	NextExpectedAt         pgtype.Date         `json:"next_expected_at"`
	CreatedAt              pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz  `json:"updated_at"`
}

type Transaction struct {
	ID                     uuid.UUID          `json:"id"`
	AccountID              uuid.UUID          `json:"account_id"`
	UserID                 uuid.UUID          `json:"user_id"`
	IdempotencyKey         string             `json:"idempotency_key"`
	ReferenceNumber        *string            `json:"reference_number"`
	Amount                 model.Money        `json:"amount"`
	Currency               string             `json:"currency"`
	Direction              TxnDirectionEnum   `json:"direction"`
	OriginalAmount         model.Money        `json:"original_amount"`
	OriginalCurrency       *string            `json:"original_currency"`
	ExchangeRate           pgtype.Numeric     `json:"exchange_rate"`
	Description            string             `json:"description"`
	CounterpartyName       *string            `json:"counterparty_name"`
	CounterpartyIdentifier *string            `json:"counterparty_identifier"`
	PaymentMode            *PaymentModeEnum   `json:"payment_mode"`
	TxnDate                pgtype.Date        `json:"txn_date"`
	PostedDate             pgtype.Date        `json:"posted_date"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type TransactionEnrichment struct {
	TransactionID         uuid.UUID          `json:"transaction_id"`
	DescriptionNormalized *string            `json:"description_normalized"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	TransferID            pgtype.UUID        `json:"transfer_id"`
	TransferType          *TransferTypeEnum  `json:"transfer_type"`
	RefundOfTransactionID pgtype.UUID        `json:"refund_of_transaction_id"`
	RecurringPaymentID    pgtype.UUID        `json:"recurring_payment_id"`
	Notes                 *string            `json:"notes"`
	NotesUpdatedAt        pgtype.Timestamptz `json:"notes_updated_at"`
	Embedding             *pgvector.Vector   `json:"embedding"`
	EmbeddingModel        *string            `json:"embedding_model"`
	TaggingStatus         TaggingStatusEnum  `json:"tagging_status"`
	Metadata              []byte             `json:"metadata"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type TransactionLabel struct {
	TransactionID uuid.UUID           `json:"transaction_id"`
	LabelID       uuid.UUID           `json:"label_id"`
	Source        DetectionSourceEnum `json:"source"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
}

type TransactionSplit struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	Amount        model.Money        `json:"amount"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TransactionSplitLabel struct {
	SplitID uuid.UUID `json:"split_id"`
	LabelID uuid.UUID `json:"label_id"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Timezone    string             `json:"timezone"`
	Preferences []byte             `json:"preferences"`
	ApiKeyHash  []byte             `json:"api_key_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VTransaction struct {
	ID                     uuid.UUID          `json:"id"`
	AccountID              uuid.UUID          `json:"account_id"`
	UserID                 uuid.UUID          `json:"user_id"`
	IdempotencyKey         string             `json:"idempotency_key"`
	ReferenceNumber        *string            `json:"reference_number"`
	Amount                 int64              `json:"amount"`
	Currency               string             `json:"currency"`
	Direction              TxnDirectionEnum   `json:"direction"`
	OriginalAmount         *int64             `json:"original_amount"`
	OriginalCurrency       *string            `json:"original_currency"`
	ExchangeRate           pgtype.Numeric     `json:"exchange_rate"`
	Description            string             `json:"description"`
	CounterpartyName       *string            `json:"counterparty_name"`
	CounterpartyIdentifier *string            `json:"counterparty_identifier"`
	PaymentMode            *PaymentModeEnum   `json:"payment_mode"`
	TxnDate                pgtype.Date        `json:"txn_date"`
	PostedDate             pgtype.Date        `json:"posted_date"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	DescriptionNormalized  *string            `json:"description_normalized"`
	CategoryID             pgtype.UUID        `json:"category_id"`
	TransferID             pgtype.UUID        `json:"transfer_id"`
	TransferType           *TransferTypeEnum  `json:"transfer_type"`
	RefundOfTransactionID  pgtype.UUID        `json:"refund_of_transaction_id"`
	RecurringPaymentID     pgtype.UUID        `json:"recurring_payment_id"`
	Notes                  *string            `json:"notes"`
	NotesUpdatedAt         pgtype.Timestamptz `json:"notes_updated_at"`
	Embedding              *pgvector.Vector   `json:"embedding"`
	EmbeddingModel         *string            `json:"embedding_model"`
	TaggingStatus          *TaggingStatusEnum `json:"tagging_status"`
	Metadata               []byte             `json:"metadata"`
	EnrichedAt             pgtype.Timestamptz `json:"enriched_at"`
}
