// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error
	AddTransactionLabel(ctx context.Context, arg AddTransactionLabelParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (AgentMemory, error)
	CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ConversationSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateMemory(ctx context.Context, id uuid.UUID) error
	DeactivateRecurringPayment(ctx context.Context, id uuid.UUID) error
	FinishImportRun(ctx context.Context, arg FinishImportRunParams) error
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountDetails(ctx context.Context, accountID uuid.UUID) (AccountDetail, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetIdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error)
	GetLabelBySlug(ctx context.Context, slug string) (Label, error)
	GetRecurringPaymentByID(ctx context.Context, id uuid.UUID) (RecurringPayment, error)
	GetSession(ctx context.Context, id uuid.UUID) (ConversationSession, error)
	GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (VTransaction, error)
	GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (uuid.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	InsertTransactionEnrichment(ctx context.Context, transactionID uuid.UUID) error
	ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListImportRuns(ctx context.Context, userID uuid.UUID) ([]ImportRun, error)
	ListLabels(ctx context.Context, userID pgtype.UUID) ([]Label, error)
	ListMemories(ctx context.Context, arg ListMemoriesParams) ([]AgentMemory, error)
	ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ConversationMessage, error)
	ListRecurringPayments(ctx context.Context, userID uuid.UUID) ([]RecurringPayment, error)
	ListSubCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	ListTopLevelCategories(ctx context.Context) ([]Category, error)
	ListTransactionLabels(ctx context.Context, transactionID uuid.UUID) ([]Label, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]VTransaction, error)
	ListTransactionsByLabel(ctx context.Context, arg ListTransactionsByLabelParams) ([]VTransaction, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ConversationSession, error)
	ListUsers(ctx context.Context) ([]User, error)
	RecallMemoriesByTags(ctx context.Context, arg RecallMemoriesByTagsParams) ([]AgentMemory, error)
	RemoveTransactionLabel(ctx context.Context, arg RemoveTransactionLabelParams) error
	SaveMessage(ctx context.Context, arg SaveMessageParams) (ConversationMessage, error)
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateEnrichment(ctx context.Context, arg UpdateEnrichmentParams) error
	UpdateImportRunCounts(ctx context.Context, arg UpdateImportRunCountsParams) error
	UpdateRecurringLastCharged(ctx context.Context, arg UpdateRecurringLastChargedParams) error
	UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error
	UpdateUserDOB(ctx context.Context, arg UpdateUserDOBParams) (User, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	UpsertAccountDetails(ctx context.Context, arg UpsertAccountDetailsParams) error
}

var _ Querier = (*Queries)(nil)
