// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/pushkaranand/finagent/internal/model"
)

const createRecurringPayment = `-- name: CreateRecurringPayment :one
INSERT INTO recurring_payments (
    user_id, account_id, name, category_id,
    expected_amount, amount_variance, frequency, approximate_day,
    payment_mode, counterparty_identifier, counterparty_name,
    detection_source, last_charged_at, next_expected_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14
) RETURNING id, user_id, account_id, name, category_id, expected_amount, amount_variance, frequency, approximate_day, payment_mode, counterparty_identifier, counterparty_name, detection_source, is_active, last_charged_at, next_expected_at, created_at, updated_at
`

type CreateRecurringPaymentParams struct {
	UserID                 uuid.UUID           `json:"user_id"`
	AccountID              uuid.UUID           `json:"account_id"`
	Name                   string              `json:"name"`
	CategoryID             pgtype.UUID         `json:"category_id"`
	ExpectedAmount         model.Money         `json:"expected_amount"`
	AmountVariance         model.Money         `json:"amount_variance"`
	Frequency              FrequencyEnum       `json:"frequency"`
	ApproximateDay         *int16              `json:"approximate_day"`
	PaymentMode            *RecurringModeEnum  `json:"payment_mode"`
	CounterpartyIdentifier *string             `json:"counterparty_identifier"`
	CounterpartyName       *string             `json:"counterparty_name"`
	DetectionSource        DetectionSourceEnum `json:"detection_source"`
	LastChargedAt          pgtype.Date         `json:"last_charged_at"`
	NextExpectedAt         pgtype.Date         `json:"next_expected_at"`
}

func (q *Queries) CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createRecurringPayment,
		arg.UserID,
		arg.AccountID,
		arg.Name,
		arg.CategoryID,
		arg.ExpectedAmount,
		arg.AmountVariance,
		arg.Frequency,
		arg.ApproximateDay,
		arg.PaymentMode,
		arg.CounterpartyIdentifier,
		arg.CounterpartyName,
		arg.DetectionSource,
		arg.LastChargedAt,
		arg.NextExpectedAt,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.CategoryID,
		&i.ExpectedAmount,
		&i.AmountVariance,
		&i.Frequency,
		&i.ApproximateDay,
		&i.PaymentMode,
		&i.CounterpartyIdentifier,
		&i.CounterpartyName,
		&i.DetectionSource,
		&i.IsActive,
		&i.LastChargedAt,
		&i.NextExpectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRecurringPayment = `-- name: DeactivateRecurringPayment :exec
UPDATE recurring_payments SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateRecurringPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateRecurringPayment, id)
	return err
}

const getRecurringPaymentByID = `-- name: GetRecurringPaymentByID :one
SELECT id, user_id, account_id, name, category_id, expected_amount, amount_variance, frequency, approximate_day, payment_mode, counterparty_identifier, counterparty_name, detection_source, is_active, last_charged_at, next_expected_at, created_at, updated_at FROM recurring_payments WHERE id = $1
`

func (q *Queries) GetRecurringPaymentByID(ctx context.Context, id uuid.UUID) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getRecurringPaymentByID, id)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.CategoryID,
		&i.ExpectedAmount,
		&i.AmountVariance,
		&i.Frequency,
		&i.ApproximateDay,
		&i.PaymentMode,
		&i.CounterpartyIdentifier,
		&i.CounterpartyName,
		&i.DetectionSource,
		&i.IsActive,
		&i.LastChargedAt,
		&i.NextExpectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecurringPayments = `-- name: ListRecurringPayments :many
SELECT id, user_id, account_id, name, category_id, expected_amount, amount_variance, frequency, approximate_day, payment_mode, counterparty_identifier, counterparty_name, detection_source, is_active, last_charged_at, next_expected_at, created_at, updated_at FROM recurring_payments
WHERE user_id = $1 AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListRecurringPayments(ctx context.Context, userID uuid.UUID) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listRecurringPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringPayment
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Name,
			&i.CategoryID,
			&i.ExpectedAmount,
			&i.AmountVariance,
			&i.Frequency,
			&i.ApproximateDay,
			&i.PaymentMode,
			&i.CounterpartyIdentifier,
			&i.CounterpartyName,
			&i.DetectionSource,
			&i.IsActive,
			&i.LastChargedAt,
			&i.NextExpectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringLastCharged = `-- name: UpdateRecurringLastCharged :exec
UPDATE recurring_payments SET
    last_charged_at  = $2,
    next_expected_at = $3,
    updated_at       = NOW()
WHERE id = $1
`

type UpdateRecurringLastChargedParams struct {
	ID             uuid.UUID   `json:"id"`
	LastChargedAt  pgtype.Date `json:"last_charged_at"`
	NextExpectedAt pgtype.Date `json:"next_expected_at"`
}

func (q *Queries) UpdateRecurringLastCharged(ctx context.Context, arg UpdateRecurringLastChargedParams) error {
	_, err := q.db.Exec(ctx, updateRecurringLastCharged, arg.ID, arg.LastChargedAt, arg.NextExpectedAt)
	return err
}
