// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	model "github.com/pushkaranand/finagent/internal/model"
)

const getIdempotencyKeyExists = `-- name: GetIdempotencyKeyExists :one
SELECT EXISTS(SELECT 1 FROM transactions WHERE idempotency_key = $1)
`

func (q *Queries) GetIdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyExists, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSpendingByCategory = `-- name: GetSpendingByCategory :many
SELECT
    c.id AS category_id,
    c.slug AS category_slug,
    c.name AS category_name,
    c.depth,
    SUM(t.amount) AS total_amount,
    COUNT(*) AS txn_count
FROM v_transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.direction = 'debit'
  AND t.txn_date >= $2
  AND t.txn_date <= $3
  AND ($4::uuid IS NULL OR t.account_id = $4::uuid)
GROUP BY c.id, c.slug, c.name, c.depth
ORDER BY total_amount DESC
`

type GetSpendingByCategoryParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	AccountID pgtype.UUID `json:"account_id"`
}

type GetSpendingByCategoryRow struct {
	CategoryID   uuid.UUID `json:"category_id"`
	CategorySlug string    `json:"category_slug"`
	CategoryName string    `json:"category_name"`
	Depth        int16     `json:"depth"`
	TotalAmount  int64     `json:"total_amount"`
	TxnCount     int64     `json:"txn_count"`
}

func (q *Queries) GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getSpendingByCategory,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpendingByCategoryRow
	for rows.Next() {
		var i GetSpendingByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategorySlug,
			&i.CategoryName,
			&i.Depth,
			&i.TotalAmount,
			&i.TxnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, user_id, idempotency_key, reference_number, amount, currency, direction, original_amount, original_currency, exchange_rate, description, counterparty_name, counterparty_identifier, payment_mode, txn_date, posted_date, created_at, description_normalized, category_id, transfer_id, transfer_type, refund_of_transaction_id, recurring_payment_id, notes, notes_updated_at, embedding, embedding_model, tagging_status, metadata, enriched_at FROM v_transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (VTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i VTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.ReferenceNumber,
		&i.Amount,
		&i.Currency,
		&i.Direction,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.ExchangeRate,
		&i.Description,
		&i.CounterpartyName,
		&i.CounterpartyIdentifier,
		&i.PaymentMode,
		&i.TxnDate,
		&i.PostedDate,
		&i.CreatedAt,
		&i.DescriptionNormalized,
		&i.CategoryID,
		&i.TransferID,
		&i.TransferType,
		&i.RefundOfTransactionID,
		&i.RecurringPaymentID,
		&i.Notes,
		&i.NotesUpdatedAt,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.TaggingStatus,
		&i.Metadata,
		&i.EnrichedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    account_id, user_id, idempotency_key, reference_number,
    amount, currency, direction,
    original_amount, original_currency, exchange_rate,
    description, counterparty_name, counterparty_identifier,
    payment_mode, txn_date, posted_date
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16
)
RETURNING id, account_id, user_id, idempotency_key, reference_number, amount, currency, direction, original_amount, original_currency, exchange_rate, description, counterparty_name, counterparty_identifier, payment_mode, txn_date, posted_date, created_at
`

type InsertTransactionParams struct {
	AccountID              uuid.UUID        `json:"account_id"`
	UserID                 uuid.UUID        `json:"user_id"`
	IdempotencyKey         string           `json:"idempotency_key"`
	ReferenceNumber        *string          `json:"reference_number"`
	Amount                 model.Money      `json:"amount"`
	Currency               string           `json:"currency"`
	Direction              TxnDirectionEnum `json:"direction"`
	OriginalAmount         model.Money      `json:"original_amount"`
	OriginalCurrency       *string          `json:"original_currency"`
	ExchangeRate           pgtype.Numeric   `json:"exchange_rate"`
	Description            string           `json:"description"`
	CounterpartyName       *string          `json:"counterparty_name"`
	CounterpartyIdentifier *string          `json:"counterparty_identifier"`
	PaymentMode            *PaymentModeEnum `json:"payment_mode"`
	TxnDate                pgtype.Date      `json:"txn_date"`
	PostedDate             pgtype.Date      `json:"posted_date"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.AccountID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.ReferenceNumber,
		arg.Amount,
		arg.Currency,
		arg.Direction,
		arg.OriginalAmount,
		arg.OriginalCurrency,
		arg.ExchangeRate,
		arg.Description,
		arg.CounterpartyName,
		arg.CounterpartyIdentifier,
		arg.PaymentMode,
		arg.TxnDate,
		arg.PostedDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.ReferenceNumber,
		&i.Amount,
		&i.Currency,
		&i.Direction,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.ExchangeRate,
		&i.Description,
		&i.CounterpartyName,
		&i.CounterpartyIdentifier,
		&i.PaymentMode,
		&i.TxnDate,
		&i.PostedDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransactionEnrichment = `-- name: InsertTransactionEnrichment :exec
INSERT INTO transaction_enrichments (transaction_id)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertTransactionEnrichment(ctx context.Context, transactionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertTransactionEnrichment, transactionID)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, user_id, idempotency_key, reference_number, amount, currency, direction, original_amount, original_currency, exchange_rate, description, counterparty_name, counterparty_identifier, payment_mode, txn_date, posted_date, created_at, description_normalized, category_id, transfer_id, transfer_type, refund_of_transaction_id, recurring_payment_id, notes, notes_updated_at, embedding, embedding_model, tagging_status, metadata, enriched_at FROM v_transactions
WHERE user_id = $1
  AND ($2::date IS NULL OR txn_date >= $2::date)
  AND ($3::date IS NULL OR txn_date <= $3::date)
  AND ($4::uuid IS NULL OR account_id = $4::uuid)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
  AND ($6::bigint IS NULL OR amount >= $6::bigint)
  AND ($7::bigint IS NULL OR amount <= $7::bigint)
  AND ($8::payment_mode_enum IS NULL OR payment_mode = $8::payment_mode_enum)
  AND ($9::text IS NULL OR counterparty_identifier = $9::text)
  AND ($10::txn_direction_enum IS NULL OR direction = $10::txn_direction_enum)
ORDER BY txn_date DESC, created_at DESC
LIMIT $12 OFFSET $11
`

type ListTransactionsParams struct {
	UserID                 uuid.UUID         `json:"user_id"`
	FromDate               pgtype.Date       `json:"from_date"`
	ToDate                 pgtype.Date       `json:"to_date"`
	AccountID              pgtype.UUID       `json:"account_id"`
	CategoryID             pgtype.UUID       `json:"category_id"`
	MinAmount              *int64            `json:"min_amount"`
	MaxAmount              *int64            `json:"max_amount"`
	PaymentMode            *PaymentModeEnum  `json:"payment_mode"`
	CounterpartyIdentifier *string           `json:"counterparty_identifier"`
	Direction              *TxnDirectionEnum `json:"direction"`
	PageOffset             int32             `json:"page_offset"`
	PageLimit              int32             `json:"page_limit"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]VTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
		arg.CategoryID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.PaymentMode,
		arg.CounterpartyIdentifier,
		arg.Direction,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VTransaction
	for rows.Next() {
		var i VTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.IdempotencyKey,
			&i.ReferenceNumber,
			&i.Amount,
			&i.Currency,
			&i.Direction,
			&i.OriginalAmount,
			&i.OriginalCurrency,
			&i.ExchangeRate,
			&i.Description,
			&i.CounterpartyName,
			&i.CounterpartyIdentifier,
			&i.PaymentMode,
			&i.TxnDate,
			&i.PostedDate,
			&i.CreatedAt,
			&i.DescriptionNormalized,
			&i.CategoryID,
			&i.TransferID,
			&i.TransferType,
			&i.RefundOfTransactionID,
			&i.RecurringPaymentID,
			&i.Notes,
			&i.NotesUpdatedAt,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.TaggingStatus,
			&i.Metadata,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByLabel = `-- name: ListTransactionsByLabel :many
SELECT vt.id, vt.account_id, vt.user_id, vt.idempotency_key, vt.reference_number, vt.amount, vt.currency, vt.direction, vt.original_amount, vt.original_currency, vt.exchange_rate, vt.description, vt.counterparty_name, vt.counterparty_identifier, vt.payment_mode, vt.txn_date, vt.posted_date, vt.created_at, vt.description_normalized, vt.category_id, vt.transfer_id, vt.transfer_type, vt.refund_of_transaction_id, vt.recurring_payment_id, vt.notes, vt.notes_updated_at, vt.embedding, vt.embedding_model, vt.tagging_status, vt.metadata, vt.enriched_at FROM v_transactions vt
JOIN transaction_labels tl ON tl.transaction_id = vt.id
WHERE tl.label_id = $1
  AND vt.user_id = $2
ORDER BY vt.txn_date DESC
LIMIT $4 OFFSET $3
`

type ListTransactionsByLabelParams struct {
	LabelID    uuid.UUID `json:"label_id"`
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListTransactionsByLabel(ctx context.Context, arg ListTransactionsByLabelParams) ([]VTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByLabel,
		arg.LabelID,
		arg.UserID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VTransaction
	for rows.Next() {
		var i VTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.IdempotencyKey,
			&i.ReferenceNumber,
			&i.Amount,
			&i.Currency,
			&i.Direction,
			&i.OriginalAmount,
			&i.OriginalCurrency,
			&i.ExchangeRate,
			&i.Description,
			&i.CounterpartyName,
			&i.CounterpartyIdentifier,
			&i.PaymentMode,
			&i.TxnDate,
			&i.PostedDate,
			&i.CreatedAt,
			&i.DescriptionNormalized,
			&i.CategoryID,
			&i.TransferID,
			&i.TransferType,
			&i.RefundOfTransactionID,
			&i.RecurringPaymentID,
			&i.Notes,
			&i.NotesUpdatedAt,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.TaggingStatus,
			&i.Metadata,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrichment = `-- name: UpdateEnrichment :exec
UPDATE transaction_enrichments SET
    description_normalized   = COALESCE($1, description_normalized),
    category_id              = COALESCE($2, category_id),
    transfer_id              = COALESCE($3, transfer_id),
    transfer_type            = COALESCE($4, transfer_type),
    refund_of_transaction_id = COALESCE($5, refund_of_transaction_id),
    recurring_payment_id     = COALESCE($6, recurring_payment_id),
    notes                    = COALESCE($7, notes),
    notes_updated_at         = CASE WHEN $7::text IS NOT NULL THEN NOW() ELSE notes_updated_at END,
    tagging_status           = COALESCE($8, tagging_status),
    updated_at               = NOW()
WHERE transaction_id = $9
`

type UpdateEnrichmentParams struct {
	DescriptionNormalized *string            `json:"description_normalized"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	TransferID            pgtype.UUID        `json:"transfer_id"`
	TransferType          *TransferTypeEnum  `json:"transfer_type"`
	RefundOfTransactionID pgtype.UUID        `json:"refund_of_transaction_id"`
	RecurringPaymentID    pgtype.UUID        `json:"recurring_payment_id"`
	Notes                 *string            `json:"notes"`
	TaggingStatus         *TaggingStatusEnum `json:"tagging_status"`
	TransactionID         uuid.UUID          `json:"transaction_id"`
}

func (q *Queries) UpdateEnrichment(ctx context.Context, arg UpdateEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateEnrichment,
		arg.DescriptionNormalized,
		arg.CategoryID,
		arg.TransferID,
		arg.TransferType,
		arg.RefundOfTransactionID,
		arg.RecurringPaymentID,
		arg.Notes,
		arg.TaggingStatus,
		arg.TransactionID,
	)
	return err
}
