// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zerodha.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteZerodhaEquityHoldings = `-- name: DeleteZerodhaEquityHoldings :exec
DELETE FROM zerodha_equity_holdings WHERE account_id = $1
`

func (q *Queries) DeleteZerodhaEquityHoldings(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteZerodhaEquityHoldings, accountID)
	return err
}

const deleteZerodhaMFHoldings = `-- name: DeleteZerodhaMFHoldings :exec
DELETE FROM zerodha_mf_holdings WHERE account_id = $1
`

func (q *Queries) DeleteZerodhaMFHoldings(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteZerodhaMFHoldings, accountID)
	return err
}

const deleteZerodhaToken = `-- name: DeleteZerodhaToken :exec
DELETE FROM zerodha_tokens WHERE user_id = $1
`

func (q *Queries) DeleteZerodhaToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteZerodhaToken, userID)
	return err
}

const getZerodhaEquityHoldingsByType = `-- name: GetZerodhaEquityHoldingsByType :many
SELECT
    CASE WHEN LEFT(tradingsymbol, 3) = 'SGB' THEN 'sgb' ELSE 'equity' END AS holding_type,
    COUNT(*)                         AS holding_count,
    SUM(quantity * last_price_paise) AS current_value_paise,
    SUM(quantity * avg_price_paise)  AS invested_value_paise,
    SUM(pnl_paise)                   AS total_pnl_paise
FROM zerodha_equity_holdings
WHERE user_id = $1
GROUP BY holding_type
`

type GetZerodhaEquityHoldingsByTypeRow struct {
	HoldingType        string `json:"holding_type"`
	HoldingCount       int64  `json:"holding_count"`
	CurrentValuePaise  int64  `json:"current_value_paise"`
	InvestedValuePaise int64  `json:"invested_value_paise"`
	TotalPnlPaise      int64  `json:"total_pnl_paise"`
}

func (q *Queries) GetZerodhaEquityHoldingsByType(ctx context.Context, userID uuid.UUID) ([]GetZerodhaEquityHoldingsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getZerodhaEquityHoldingsByType, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetZerodhaEquityHoldingsByTypeRow
	for rows.Next() {
		var i GetZerodhaEquityHoldingsByTypeRow
		if err := rows.Scan(
			&i.HoldingType,
			&i.HoldingCount,
			&i.CurrentValuePaise,
			&i.InvestedValuePaise,
			&i.TotalPnlPaise,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZerodhaEquitySummary = `-- name: GetZerodhaEquitySummary :one
SELECT
    COUNT(*)                         AS holding_count,
    SUM(quantity * last_price_paise) AS current_value_paise,
    SUM(quantity * avg_price_paise)  AS invested_value_paise,
    SUM(pnl_paise)                   AS total_pnl_paise,
    MAX(synced_at)                   AS synced_at
FROM zerodha_equity_holdings
WHERE user_id = $1
`

type GetZerodhaEquitySummaryRow struct {
	HoldingCount       int64       `json:"holding_count"`
	CurrentValuePaise  int64       `json:"current_value_paise"`
	InvestedValuePaise int64       `json:"invested_value_paise"`
	TotalPnlPaise      int64       `json:"total_pnl_paise"`
	SyncedAt           interface{} `json:"synced_at"`
}

func (q *Queries) GetZerodhaEquitySummary(ctx context.Context, userID uuid.UUID) (GetZerodhaEquitySummaryRow, error) {
	row := q.db.QueryRow(ctx, getZerodhaEquitySummary, userID)
	var i GetZerodhaEquitySummaryRow
	err := row.Scan(
		&i.HoldingCount,
		&i.CurrentValuePaise,
		&i.InvestedValuePaise,
		&i.TotalPnlPaise,
		&i.SyncedAt,
	)
	return i, err
}

const getZerodhaEquitySyncedAt = `-- name: GetZerodhaEquitySyncedAt :one
SELECT MAX(synced_at) AS synced_at FROM zerodha_equity_holdings WHERE account_id = $1
`

func (q *Queries) GetZerodhaEquitySyncedAt(ctx context.Context, accountID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getZerodhaEquitySyncedAt, accountID)
	var synced_at interface{}
	err := row.Scan(&synced_at)
	return synced_at, err
}

const getZerodhaMFSummary = `-- name: GetZerodhaMFSummary :one
SELECT
    COUNT(*)                   AS holding_count,
    SUM(units * nav_paise)     AS current_value_paise,
    SUM(units * avg_nav_paise) AS invested_value_paise,
    SUM(pnl_paise)             AS total_pnl_paise,
    MAX(synced_at)             AS synced_at
FROM zerodha_mf_holdings
WHERE user_id = $1
`

type GetZerodhaMFSummaryRow struct {
	HoldingCount       int64       `json:"holding_count"`
	CurrentValuePaise  int64       `json:"current_value_paise"`
	InvestedValuePaise int64       `json:"invested_value_paise"`
	TotalPnlPaise      int64       `json:"total_pnl_paise"`
	SyncedAt           interface{} `json:"synced_at"`
}

func (q *Queries) GetZerodhaMFSummary(ctx context.Context, userID uuid.UUID) (GetZerodhaMFSummaryRow, error) {
	row := q.db.QueryRow(ctx, getZerodhaMFSummary, userID)
	var i GetZerodhaMFSummaryRow
	err := row.Scan(
		&i.HoldingCount,
		&i.CurrentValuePaise,
		&i.InvestedValuePaise,
		&i.TotalPnlPaise,
		&i.SyncedAt,
	)
	return i, err
}

const getZerodhaMFSyncedAt = `-- name: GetZerodhaMFSyncedAt :one
SELECT MAX(synced_at) AS synced_at FROM zerodha_mf_holdings WHERE account_id = $1
`

func (q *Queries) GetZerodhaMFSyncedAt(ctx context.Context, accountID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getZerodhaMFSyncedAt, accountID)
	var synced_at interface{}
	err := row.Scan(&synced_at)
	return synced_at, err
}

const getZerodhaToken = `-- name: GetZerodhaToken :one
SELECT user_id, access_token, expires_at, created_at, updated_at FROM zerodha_tokens WHERE user_id = $1
`

func (q *Queries) GetZerodhaToken(ctx context.Context, userID uuid.UUID) (ZerodhaToken, error) {
	row := q.db.QueryRow(ctx, getZerodhaToken, userID)
	var i ZerodhaToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertZerodhaEquityHolding = `-- name: InsertZerodhaEquityHolding :exec
INSERT INTO zerodha_equity_holdings (
    user_id, account_id, tradingsymbol, exchange, isin,
    quantity, avg_price_paise, last_price_paise, pnl_paise, day_change_paise
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
`

type InsertZerodhaEquityHoldingParams struct {
	UserID         uuid.UUID `json:"user_id"`
	AccountID      uuid.UUID `json:"account_id"`
	Tradingsymbol  string    `json:"tradingsymbol"`
	Exchange       string    `json:"exchange"`
	Isin           *string   `json:"isin"`
	Quantity       int32     `json:"quantity"`
	AvgPricePaise  int64     `json:"avg_price_paise"`
	LastPricePaise int64     `json:"last_price_paise"`
	PnlPaise       int64     `json:"pnl_paise"`
	DayChangePaise int64     `json:"day_change_paise"`
}

func (q *Queries) InsertZerodhaEquityHolding(ctx context.Context, arg InsertZerodhaEquityHoldingParams) error {
	_, err := q.db.Exec(ctx, insertZerodhaEquityHolding,
		arg.UserID,
		arg.AccountID,
		arg.Tradingsymbol,
		arg.Exchange,
		arg.Isin,
		arg.Quantity,
		arg.AvgPricePaise,
		arg.LastPricePaise,
		arg.PnlPaise,
		arg.DayChangePaise,
	)
	return err
}

const insertZerodhaMFHolding = `-- name: InsertZerodhaMFHolding :exec
INSERT INTO zerodha_mf_holdings (
    user_id, account_id, folio, fund, tradingsymbol,
    units, avg_nav_paise, nav_paise, pnl_paise
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertZerodhaMFHoldingParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Folio         string         `json:"folio"`
	Fund          string         `json:"fund"`
	Tradingsymbol string         `json:"tradingsymbol"`
	Units         pgtype.Numeric `json:"units"`
	AvgNavPaise   int64          `json:"avg_nav_paise"`
	NavPaise      int64          `json:"nav_paise"`
	PnlPaise      int64          `json:"pnl_paise"`
}

func (q *Queries) InsertZerodhaMFHolding(ctx context.Context, arg InsertZerodhaMFHoldingParams) error {
	_, err := q.db.Exec(ctx, insertZerodhaMFHolding,
		arg.UserID,
		arg.AccountID,
		arg.Folio,
		arg.Fund,
		arg.Tradingsymbol,
		arg.Units,
		arg.AvgNavPaise,
		arg.NavPaise,
		arg.PnlPaise,
	)
	return err
}

const listZerodhaEquityHoldings = `-- name: ListZerodhaEquityHoldings :many
SELECT id, user_id, account_id, tradingsymbol, exchange, isin, quantity, avg_price_paise, last_price_paise, pnl_paise, day_change_paise, synced_at FROM zerodha_equity_holdings
WHERE user_id = $1
ORDER BY tradingsymbol
`

func (q *Queries) ListZerodhaEquityHoldings(ctx context.Context, userID uuid.UUID) ([]ZerodhaEquityHolding, error) {
	rows, err := q.db.Query(ctx, listZerodhaEquityHoldings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZerodhaEquityHolding
	for rows.Next() {
		var i ZerodhaEquityHolding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Tradingsymbol,
			&i.Exchange,
			&i.Isin,
			&i.Quantity,
			&i.AvgPricePaise,
			&i.LastPricePaise,
			&i.PnlPaise,
			&i.DayChangePaise,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZerodhaMFHoldings = `-- name: ListZerodhaMFHoldings :many
SELECT id, user_id, account_id, folio, fund, tradingsymbol, units, avg_nav_paise, nav_paise, pnl_paise, synced_at FROM zerodha_mf_holdings
WHERE user_id = $1
ORDER BY fund
`

func (q *Queries) ListZerodhaMFHoldings(ctx context.Context, userID uuid.UUID) ([]ZerodhaMfHolding, error) {
	rows, err := q.db.Query(ctx, listZerodhaMFHoldings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZerodhaMfHolding
	for rows.Next() {
		var i ZerodhaMfHolding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Folio,
			&i.Fund,
			&i.Tradingsymbol,
			&i.Units,
			&i.AvgNavPaise,
			&i.NavPaise,
			&i.PnlPaise,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertZerodhaToken = `-- name: UpsertZerodhaToken :exec
INSERT INTO zerodha_tokens (user_id, access_token, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
    access_token = EXCLUDED.access_token,
    expires_at   = EXCLUDED.expires_at,
    updated_at   = NOW()
`

type UpsertZerodhaTokenParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	AccessToken string             `json:"access_token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertZerodhaToken(ctx context.Context, arg UpsertZerodhaTokenParams) error {
	_, err := q.db.Exec(ctx, upsertZerodhaToken, arg.UserID, arg.AccessToken, arg.ExpiresAt)
	return err
}
