name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: pushkar-anand/.github/.github/workflows/go-release.yml@main
    secrets: inherit
    with:
      image-name: "jn-66"
